force-app/main/default/objects/Process_Approval__c/Process_Approval__c.object-meta.xml
<CustomObject>
    <label>Process Approval</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Process Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Approval__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Process Approvals</relationshipLabel>
    <relationshipName>Process_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Background_Check_Date__c.field-meta.xml
<CustomField>
    <fullName>Background_Check_Date__c</fullName>
    <label>Background Check Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/DIRECTV_Expiration__c.field-meta.xml
<CustomField>
    <fullName>DIRECTV_Expiration__c</fullName>
    <label>DIRECTV Id Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Drug_Screen_Date__c.field-meta.xml
<CustomField>
    <fullName>Drug_Screen_Date__c</fullName>
    <label>Drug Screen Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/ID_DirecTV__c.field-meta.xml
<CustomField>
    <fullName>ID_DirecTV__c</fullName>
    <label>ID-DirecTV</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/ID_Viasat__c.field-meta.xml
<CustomField>
    <fullName>ID_Viasat__c</fullName>
    <label>ID-Viasat</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Include_in_Scheduling_Optimization__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Scheduling_Optimization__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include in Scheduling Optimization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inventory Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Van</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
                <isActive>false</isActive>
                <label>Plant</label>
            </value>
            <value>
                <fullName>Site</fullName>
                <isActive>false</isActive>
                <label>Site</label>
            </value>
            <value>
                <fullName>Virtual</fullName>
                <isActive>false</isActive>
                <label>Virtual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/MailingCity__c.field-meta.xml
<CustomField>
    <fullName>MailingCity__c</fullName>
    <label>MailingCity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/MailingCountry__c.field-meta.xml
<CustomField>
    <fullName>MailingCountry__c</fullName>
    <label>MailingCountry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/MailingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>MailingPostalCode__c</fullName>
    <label>MailingPostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/MailingState__c.field-meta.xml
<CustomField>
    <fullName>MailingState__c</fullName>
    <label>MailingState</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/MailingStreet__c.field-meta.xml
<CustomField>
    <fullName>MailingStreet__c</fullName>
    <label>MailingStreet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Process_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Mobile_Location__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mobile Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Resource_Image__c.field-meta.xml
<CustomField>
    <fullName>Resource_Image__c</fullName>
    <label>Resource Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Dispatcher</fullName>
            </value>
            <value>
                <fullName>Dispatcher and Technician</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Service_memberships__c.field-meta.xml
<CustomField>
    <fullName>Service_memberships__c</fullName>
    <label>Service memberships</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Process Approvals (Service Resource)</relationshipLabel>
    <relationshipName>Process_Approvals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Skill_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Skill_Start_Date__c</fullName>
    <label>Skill Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Type__c</fullName>
    <label>Vendor Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AT&amp;T</fullName>
            </value>
            <value>
                <fullName>COSTCO</fullName>
            </value>
            <value>
                <fullName>DIRECTV</fullName>
            </value>
            <value>
                <fullName>T-Mobile</fullName>
            </value>
            <value>
                <fullName>Viasat</fullName>
            </value>
            <value>
                <fullName>WOW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Viasat_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Viasat_Expiration__c</fullName>
    <label>Viasat Id Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/recordTypes/Location_Approval.recordType-meta.xml
<RecordType>
    <fullName>Location_Approval</fullName>
    <active>true</active>
    <description>To approve the location records created by Dispatcher</description>
    <label>Location Approval</label>
</RecordType>

force-app/main/default/objects/Process_Approval__c/recordTypes/Service_Resource_Approval.recordType-meta.xml
<RecordType>
    <fullName>Service_Resource_Approval</fullName>
    <active>true</active>
    <label>Service Resource Approval</label>
</RecordType>

force-app/main/default/classes/PV_ProcessApprovalTriggerHandler.cls
/**
* @description       : Class for Managing Service Resources
* @author            : Impaqtive DevTeam
* @last modified on  : 11-05-2023
* @last modified by  : Impaqtive DevTeam
* Modifications Log
* Ver   Date         Author            	   Modification
* 1.0   11/05/2023   Impaqtive DevTeam     Initial Version
**/

public class PV_ProcessApprovalTriggerHandler{
    
    public static void processApprovalCallToUpdateSR(List<Process_Approval__c> newRecords, Map<Id, Process_Approval__c> oldMap){
        List<Process_Approval__c> approvedRecords = new List<Process_Approval__c>();
        Map<Id, List<Shift>>  shiftsPerProcessApproval = new Map<Id, List<Shift>>();
        Set<Id> approvedIds = new Set<Id>();
        Id serviceRecordTypeId = Schema.SObjectType.Process_Approval__c.getRecordTypeInfosByDeveloperName().get('Service_Resource_Approval').getRecordTypeId();
          String imageURL='';
        for (Process_Approval__c pa : newRecords){
            if (pa.Status__c == 'Approved' && oldMap.get(pa.Id).Status__c != 'Approved' && pa.RecordTypeId == serviceRecordTypeId){
                approvedRecords.add(pa);
                approvedIds.add(pa.Id);
            }
        }

        for (Shift targetShift : [SELECT Id, StartTime, EndTime, TimeSlotType, ServiceTerritoryId, Process_Approval__c FROM Shift WHERE Process_Approval__c IN :approvedIds]){
            if(!shiftsPerProcessApproval.keySet().contains(targetShift.Process_Approval__c)){
                shiftsPerProcessApproval.put(targetShift.Process_Approval__c, new List<Shift>());
            }
            shiftsPerProcessApproval.get(targetShift.Process_Approval__c).add(targetShift);
        }
        if (!approvedRecords.isEmpty()){
            for (Process_Approval__c pa : approvedRecords){
                //PV_CreateSR.createPS(pa.Contact__c, pa.Resource_Type__c);
                Contact con = new Contact();
                con.FirstName = pa.First_Name__c;
                con.LastName = pa.Last_Name__c;
                con.ID_DirecTV__c = pa.ID_DirecTV__c;
                con.ID_Viasat__c = pa.ID_Viasat__c;
                con.Include_in_Scheduling_Optimization__c = pa.Include_in_Scheduling_Optimization__c;
                con.AccountId = pa.Account__c;
                con.Drug_Screen_Date__c = pa.Drug_Screen_Date__c;
                con.Background_Check_Date__c = pa.Background_Check_Date__c;
                con.Email = pa.Email__c;
                con.Phone = pa.Phone__c;
                con.Time_zone__c = pa.Time_Zone__c;
                con.Vendor_Type__c = pa.Vendor_Type__c;                
                con.Mailingstreet = pa.MailingStreet__c;
                con.Mailingcity = pa.MailingCity__c;
                con.MailingstateCode =  pa.MailingState__c;
                con.MailingpostalCode = pa.MailingPostalCode__c;
                con.MailingcountryCode = pa.MailingCountry__c;
                con.Resource_Type__c=pa.Resource_Type__c;
                con.Manager__c=pa.Manager__c;
                list<String> skillList = new list<String>();
                If(!String.isBlank(pa.Skill__c)){
                     skillList = pa.Skill__c.split(',');
                }
                String img;
                if(!Test.isRunningTest()){
                    if(pa.Resource_Image__c!=null){
                       imageURL=  pa.Resource_Image__c.substringBetween(' src="', '"' );
                	   img=imageURL.unescapeHtml4();  
                    }else{
                        img=null;
                    }
                    
                    String userTimeZone = UserInfo.getTimeZone().getID();
            		PV_ManageServiceResources.submitForApprovalOrSRCreation(con, pa.Resource_Type__c,pa.Service_memberships__c,skillList,pa.Skill_Start_Date__c,pa.Viasat_Expiration__c,pa.DIRECTV_Expiration__c,null,pa.id,img, shiftsPerProcessApproval.get(pa.id), ''); 
                }
              
            }
        }
    }
    
    public static void processApprovalCallToCreateLocation(List<Process_Approval__c> newRecordsPA, Map<Id,Process_Approval__c> oldMapPA){
        try{
            List<Process_Approval__c> paRecords = new List<Process_Approval__c>();
            Id locationRecordTypeId = Schema.SObjectType.Process_Approval__c.getRecordTypeInfosByDeveloperName().get('Location_Approval').getRecordTypeId();
            for(Process_Approval__c pa : newRecordsPA){
                if(pa.Status__c == 'Approved' && oldMapPA.get(pa.Id).Status__c != pa.Status__c  && pa.RecordTypeId == locationRecordTypeId){
                    paRecords.add(pa);
                }
            }
            if(!paRecords.isEmpty()){
                List<Schema.Location> locList = new List<Schema.Location>();
                for(Process_Approval__c pa : paRecords){
                    Schema.Location loct = new Schema.Location();
                    loct.Name = pa.Location_Name__c;
                    loct.LocationType = pa.Location_Type__c;
                    loct.IsInventoryLocation = pa.Inventory_Location__c;
                    loct.Account__c = pa.Account__c;
                    loct.IsMobile = pa.Mobile_Location__c;
                    loct.Service_Resource__c = pa.Service_Resource__c;
                    locList.add(loct);
                }
                insert locList;
            }
        }
        catch(Exception ex){
            ExceptionUtil.publishException('PV_ProcessApprovalTriggerHandler.processApprovalCallToCreateLocation', ex.getLineNumber(), ex.getMessage(), ex.getStackTraceString());
        }
    }

}