force-app/main/default/objects/Process_Approval__c/Process_Approval__c.object-meta.xml
<CustomObject>
    <label>Process Approval</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Process Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Approval__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Process Approvals</relationshipLabel>
    <relationshipName>Process_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Background_Check_Date__c.field-meta.xml
<CustomField>
    <fullName>Background_Check_Date__c</fullName>
    <label>Background Check Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/DIRECTV_Expiration__c.field-meta.xml
<CustomField>
    <fullName>DIRECTV_Expiration__c</fullName>
    <label>DIRECTV Id Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Drug_Screen_Date__c.field-meta.xml
<CustomField>
    <fullName>Drug_Screen_Date__c</fullName>
    <label>Drug Screen Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/ID_DirecTV__c.field-meta.xml
<CustomField>
    <fullName>ID_DirecTV__c</fullName>
    <label>ID-DirecTV</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/ID_Viasat__c.field-meta.xml
<CustomField>
    <fullName>ID_Viasat__c</fullName>
    <label>ID-Viasat</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Include_in_Scheduling_Optimization__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Scheduling_Optimization__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include in Scheduling Optimization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inventory Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Van</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
                <isActive>false</isActive>
                <label>Plant</label>
            </value>
            <value>
                <fullName>Site</fullName>
                <isActive>false</isActive>
                <label>Site</label>
            </value>
            <value>
                <fullName>Virtual</fullName>
                <isActive>false</isActive>
                <label>Virtual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Mobile_Location__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mobile Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Dispatcher</fullName>
            </value>
            <value>
                <fullName>Dispatcher and Technician</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Service_memberships__c.field-meta.xml
<CustomField>
    <fullName>Service_memberships__c</fullName>
    <label>Service memberships</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Skill_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Skill_Start_Date__c</fullName>
    <label>Skill Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Type__c</fullName>
    <label>Vendor Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AT&amp;T</fullName>
            </value>
            <value>
                <fullName>COSTCO</fullName>
            </value>
            <value>
                <fullName>DIRECTV</fullName>
            </value>
            <value>
                <fullName>T-Mobile</fullName>
            </value>
            <value>
                <fullName>Viasat</fullName>
            </value>
            <value>
                <fullName>WOW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Approval__c/fields/Viasat_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Viasat_Expiration__c</fullName>
    <label>Viasat Id Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Approval__c/recordTypes/Location_Approval.recordType-meta.xml
<RecordType>
    <fullName>Location_Approval</fullName>
    <active>true</active>
    <description>To approve the location records created by Dispatcher</description>
    <label>Location Approval</label>
</RecordType>

force-app/main/default/objects/Process_Approval__c/recordTypes/Service_Resource_Approval.recordType-meta.xml
<RecordType>
    <fullName>Service_Resource_Approval</fullName>
    <active>true</active>
    <label>Service Resource Approval</label>
</RecordType>

force-app/main/default/classes/PV_ProcessApprovalTriggerHandlerTest.cls
/**
* @description       : Class for Managing Service Resources
* @author            : Impaqtive DevTeam
* @last modified on  : 11-05-2023
* @last modified by  : Impaqtive DevTeam
* Modifications Log
* Ver   Date         Author            	   Modification
* 1.0   11/05/2023   Impaqtive DevTeam     Initial Version
**/

@isTest
public class PV_ProcessApprovalTriggerHandlerTest {
    
    @isTest
    static void ProcessApprovalTriggerTest(){

        Account acc = PV_TestDataFactory.createAccount('Test ABC', true);
        Contact partnerContact = PV_TestDataFactory.createContact('TestFirstName', 'TestLastName', false, acc);
        OperatingHours opHrs = PV_TestDataFactory.createOperatingHours('TestHours', true);
        ServiceTerritory st = PV_TestDataFactory.createParentServiceTerritory(true, 'TestTerritory', opHrs);
        PV_ManageServiceResources.ServiceTerritoryMembership st1 = new PV_ManageServiceResources.ServiceTerritoryMembership();
        st1.StartDate = String.valueOf(Date.today());
        st1.TerritoryId = st.Id;
        st1.TerritoryType = 'Primary';
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartArray();
        gen.writeStartObject();
        gen.writeNumberField('IndexId', 0);
        gen.writeStringField('StartDate', st1.StartDate);
        gen.writeStringField('TerritoryId', st1.TerritoryId);
        gen.writeStringField('TerritoryType', st1.TerritoryType);
        gen.writeEndObject();
        gen.writeEndArray();
        String jsonString = gen.getAsString();

        Process_Approval__c pa = new Process_Approval__c();
        Id rtId = [SELECT Id FROM RecordType WHERE SobjectType = 'Process_Approval__c' AND DeveloperName = 'Service_Resource_Approval' LIMIT 1].Id;
        pa.RecordTypeId = rtId;
        pa.Resource_Type__c = 'Technician';
        pa.Background_Check_Date__c = Date.today();
        pa.Drug_Screen_Date__c = Date.today();
        pa.Service_memberships__c = jsonString;
        pa.Skill__c = 'Basic';  
        pa.Skill_Start_Date__c = Date.today();
        pa.Include_in_Scheduling_Optimization__c = true;
        pa.First_Name__c = 'TestFirstName';
        pa.Last_Name__c = 'TestLastName';
        pa.ID_DirecTV__c = '12345';
        pa.ID_Viasat__c = '67890';
        pa.Account__c = acc.Id;
        pa.Email__c = 'test@example.com';
        pa.Phone__c = '1234567890';
        pa.Time_Zone__c = 'GMT';
        pa.Vendor_Type__c = partnerContact.Vendor_Type__c;
        pa.DIRECTV_Expiration__c = Date.today().addYears(1);
        pa.Viasat_Expiration__c = Date.today().addYears(1);
        insert pa;

        List<Shift> shiftList = new List<Shift>();
        for (Integer i = 0; i < 3; i++) {
            Shift shift = new Shift();
            shift.Process_Approval__c = pa.Id;
            shift.StartTime = DateTime.now().addDays(i);
            shift.EndTime = DateTime.now().addDays(i).addHours(8);
            shift.TimeSlotType = 'Normal';
            shift.ServiceTerritoryId = st.Id;
            shiftList.add(shift);
        }
        insert shiftList;

        pa.Status__c = 'Approved';
        update pa;

        List<Shift> associatedShifts = [SELECT Id, StartTime, EndTime, TimeSlotType, ServiceTerritoryId 
                                        FROM Shift WHERE Process_Approval__c = :pa.Id];
        System.assertEquals(3, associatedShifts.size(), 'Should have 3 Shifts');
    }
    
    @isTest
    public static void processApprovalLocationTest() {

        Account acc = PV_TestDataFactory.createAccount('Test ABCD', true);

        Process_Approval__c pa = new Process_Approval__c();
        Id rtId = [SELECT Id FROM RecordType WHERE SobjectType = 'Process_Approval__c' AND DeveloperName = 'Location_Approval' LIMIT 1].Id;
        pa.RecordTypeId = rtId;
        pa.Account__c = acc.Id;
        pa.Location_Name__c = 'Test Location';
        pa.Location_Type__c = 'Warehouse';
        pa.Inventory_Location__c = true;
        pa.Mobile_Location__c = false;
        insert pa;

        pa.Status__c = 'Approved';
        update pa;

    }
}