force-app/main/default/objects/Recipient_Group__c/fields/Vendor_Program__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Group is program-specific if I&apos;m filled out.</description>
    <label>Vendor Program</label>
    <referenceTo>Vendor_Customization__c</referenceTo>
    <relationshipLabel>Recipient Group</relationshipLabel>
    <relationshipName>Recipient_Group</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/unpackaged/objects/Vendor_Customization__c.object
<CustomObject>
    <description>Each vendor’s specific program (e.g., “Verizon Fios D2D”, “Frontier NR”).</description>
    <label>Vendor Program</label>
    <nameField>
        <displayFormat>VCN-{00000}</displayFormat>
        <label>Vendor Customization Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Customization__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Versioning_Status_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vendor_Program__c/Vendor_Program__c.object-meta.xml
<CustomObject>
    <description>Placeholder for Vendor Program object</description>
    <label>Vendor Program</label>
    <pluralLabel>Vendor Programs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Vendor_Program_Recipient_Group__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Versioning_Status_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/test/TestVendorProgramRecipientGroupFactory.cls
@isTest
public class TestVendorProgramRecipientGroupFactory {

    public static Vendor_Program_Recipient_Group__c create(Boolean doInsert) {
        Vendor_Customization__c vendorProgram = TestVendorProgramFactory.createVendorWithCustomization(doInsert).customization;
        Recipient_Group__c recipientGroup = TestRecipientGroupFactory.create(doInsert);

        Vendor_Program_Recipient_Group__c vendorProgramRecipientGroup = new Vendor_Program_Recipient_Group__c(
            Vendor_Program__c = vendorProgram.Id,
            Recipient_Group__c = recipientGroup.Id,
            Is_Active__c = true,
            Status__c = 'Active',
            Filter_Logic__c = 'AND',
            Version__c = '1.0'
        );

        if (doInsert) insert vendorProgramRecipientGroup;
        return vendorProgramRecipientGroup;
    }
}