force-app/main/default/objects/POE_Event__c/POE_Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POE_Event__c/fields/POE_City__c.field-meta.xml
<CustomField>
    <fullName>POE_City__c</fullName>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE_Event__c/fields/POE_State__c.field-meta.xml
<CustomField>
    <fullName>POE_State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/POE_Event__c/fields/POE_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>POE_Street_Address__c</fullName>
    <label>Street Address</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE_Event__c/fields/POE_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>POE_Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/POE_GeoCodeEvents.cls
public class POE_GeoCodeEvents {
    @InvocableMethod(label='Geocode Events' description='Geocode Events with address updates or during creation.')
    public static void updateEvents(List<POE_Event__c> events) {
        String address =
            events[0].POE_Street_Address__c +
            ', ' +
            events[0].POE_City__c +
            ', ' +
            events[0].POE_State__c +
            ' ' +
            events[0].POE_Zip_Code__c +
            ' USA';
        geoCodeRecord(address, events[0].Id);
    }

    @future(callout=true)
    public static void geoCodeRecord(String address, String recordId) {
        Map<string, object> options = new Map<String, Object>{ 'version' => '1', 'address' => address };
        Map<String, Object> response = new Map<String, Object>();
        if (!Test.isRunningTest()) {
            response = maps.API.Geocode(options);
        } else {
            Map<String, Object> position = new Map<String, Object>();
            position.put('lat', 37.7897784);
            position.put('lng', -122.3973206);
            Map<String, Object> data = new Map<String, Object>();
            data.put('position', position);
            response.put('data', data);
        }
        try {
            Map<String, Object> data = (Map<String, Object>) response.get('data');
            Map<String, Object> position = (Map<String, Object>) data.get('position');
            Decimal lat = (Decimal) position.get('lat');
            Decimal lng = (Decimal) position.get('lng');
            POE_Event__c ev = [
                SELECT Id, Location__Latitude__s, Location__Longitude__s
                FROM POE_Event__c
                WHERE Id = :recordId
            ];
            ev.Location__Latitude__s = lat;
            ev.Location__Longitude__s = lng;
            update ev;
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }

    public class Output {
        public String baseUrl;
        public Data data;
        public String source;
        public String success;
    }

    public class Data {
        public String houseNumber;
        public String matchLevel;
        public Integer score;
        public String country;
        public String postal;
        public String state;
        public String city;
        public String street;
        public String fullAddress;
        public Position position;
    }

    public class Position {
        public Decimal lng;
        public Decimal lat;
    }
}