force-app/main/default/objects/POE_Event__c/POE_Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POE_Event__c/fields/POE_City__c.field-meta.xml
<CustomField>
    <fullName>POE_City__c</fullName>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE_Event__c/fields/POE_State__c.field-meta.xml
<CustomField>
    <fullName>POE_State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/POE_Event__c/fields/POE_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>POE_Street_Address__c</fullName>
    <label>Street Address</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE_Event__c/fields/POE_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>POE_Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/POE_GeoCodeEventsTest.cls
@isTest
public with sharing class POE_GeoCodeEventsTest {
    @isTest
    private static void createEventTest() {
        Test.startTest();
        POE_Event__c ev = new POE_Event__c();
        ev.Name = 'Test';
        ev.POE_City__c = 'San Francisco';
        ev.POE_State__c = 'California';
        ev.POE_Street_Address__c = '417 Mission Street';
        ev.POE_Zip_Code__c = '94105';
        insert ev;
        Test.stopTest();
        POE_Event__c updatedEv = [SELECT Id, Location__Latitude__s, Location__Longitude__s FROM POE_Event__c LIMIT 1];
        POE_GeoCodeEvents.geoCodeRecord('InvalidAddress', 'InvalidRecordId');
        System.assertEquals(37.7897784, updatedEv.Location__Latitude__s, 'Method not correclty invocated');
        System.assertEquals(-122.3973206, updatedEv.Location__Longitude__s, 'Method not correclty invocated');
    }
}