force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Object used to store error logs. (PER-2431)</description>
    <label>Chuzo Error Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chuzo Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <description>Name of the apex class or lightning web component in which the error occurred. (PER-2431)</description>
    <label>Component</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>If internal, this is the error message from the exception + the line number, if API call, then it is the response. (PER-2431)</description>
    <label>Error</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <description>Provider selected by the user in Chuzo. Leave empty if not applicable. (PER-2431)</description>
    <label>Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Determines if the error is coming from an API or if it is internal. (PER-2431)</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Error</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
            <value>
                <fullName>Lead Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PV_SAStatusChangeToDispatchBatchTest.cls
@isTest
public class PV_SAStatusChangeToDispatchBatchTest {
    public static Integer numberOfRecords = 100;

    @testSetup
    static void testData() {
        Account acct = PV_TestDataFactory.createAccount('TestAcc', true);
        Contact con = PV_TestDataFactory.createContact('firstName', 'lastName',true,acct);
        
        OperatingHours opHrs = PV_TestDataFactory.createOperatingHours('East - Mon-Fri 8am - 5pm', true);
        ServiceTerritory pst = PV_TestDataFactory.createParentServiceTerritory(true,'ST-01',opHrs);
        ServiceTerritory childServiceTerritory = PV_TestDataFactory.createServiceTerritoryForAccount(true,acct,pst);

        User usr;
        System.runAs(new User(Id = Userinfo.getUserId())) {
            usr = PV_TestDataFactory.createTechnicianUser(true,con);
            PV_TestDataFactory.assignPermissionSetGroupToUser(true,usr,'FSL_Technician');
        }
        
        ServiceResource sr = PV_TestDataFactory.createServiceResource(true,acct,con,usr);
        ServiceTerritoryMember stm = PV_TestDataFactory.createServiceTerritoryMember(true,sr,childServiceTerritory,'P');
        WorkType wt = PV_TestDataFactory.createWorkType('ImpSkill',true);

        WorkOrder wo = new WorkOrder();
        wo.Status = 'Unscheduled';
        wo.OwnerId = usr.Id;
        wo.WorkTypeId = wt.Id;
        wo.Vendor__c = 'T-Mobile';
        insert wo;
        
        List<ServiceAppointment> saList = new List<ServiceAppointment>();
        
        for (Integer i = 1; i <= numberOfRecords; i++) {
            ServiceAppointment saTest = new ServiceAppointment();
            saTest.Description = 'TestingSA' + i;
            saTest.ParentRecordId = wo.Id;
            saTest.FSSK__FSK_Work_Order__c = wo.Id;
            saTest.ServiceTerritoryId = pst.Id;
            saTest.WorkTypeId = wt.Id;
            saTest.Status = 'Scheduled';
            saTest.FSSK__FSK_Assigned_Service_Resource__c = sr.Id;
            saTest.SchedStartTime = System.now();
            saTest.SchedEndTime = System.now().addHours(2);
            saTest.DueDate = System.today().adddays(2);
            saList.add(saTest);
        }
        
        if (!saList.isEmpty()) {
            insert saList;
        }
    }

    @isTest
    static void testBatch() {
        Test.startTest();
        PV_SAStatusChangeToDispatchBatch batchInstance = new PV_SAStatusChangeToDispatchBatch();
        Database.executeBatch(batchInstance);
        Test.stopTest();

        List<ServiceAppointment> serviceAppointments = [SELECT Id, Status FROM ServiceAppointment WHERE Status = 'Dispatched'];
        Assert.areEqual(
            numberOfRecords,
            serviceAppointments.size(),
            'testBatch: The number of ServiceAppointment records with status "Dispatched" does not match the expected value.'
        );
    }
    
    @isTest
    static void testBatchException() {
        PV_SAStatusChangeToDispatchBatch.throwException = true;
        
        Test.startTest();
        PV_SAStatusChangeToDispatchBatch batchInstance = new PV_SAStatusChangeToDispatchBatch();
        Database.executeBatch(batchInstance);
        Test.stopTest();

        List<Error_Log__c> errors = [
            SELECT  Id, Type__c, Provider__c, Component__c, Error__c, CreatedDate
            FROM    Error_Log__c
            WHERE   Component__c = :PV_SAStatusChangeToDispatchBatch.class.getName()
        ];

        Assert.areNotEqual(0, errors.size(), 'testBatchException: Error logs were not created as expected.');
    }
}