force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Object used to store error logs. (PER-2431)</description>
    <label>Chuzo Error Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chuzo Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <description>Name of the apex class or lightning web component in which the error occurred. (PER-2431)</description>
    <label>Component</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>The endpoint that is failing, is only applicable if the type is ‘API Error’. (PER-2431)</description>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>If internal, this is the error message from the exception + the line number, if API call, then it is the response. (PER-2431)</description>
    <label>Error</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to the buyflow that failed. (PER-2431)</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <description>Provider selected by the user in Chuzo. Leave empty if not applicable. (PER-2431)</description>
    <label>Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Provider_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Provider_Subtype__c</fullName>
    <label>Provider Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beam</fullName>
            </value>
            <value>
                <fullName>Stream</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>The request for the API call, is only applicable if the type is ‘API Error’. (PER-2431)</description>
    <label>Request</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Tab__c.field-meta.xml
<CustomField>
    <fullName>Tab__c</fullName>
    <description>Tab in which the error occurred in Chuzo. Leave empty if not applicable. (PER-2431)</description>
    <label>Tab</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Determines if the error is coming from an API or if it is internal. (PER-2431)</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Error</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
            <value>
                <fullName>Lead Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ErrorLogModelTest.cls
@isTest
public class ErrorLogModelTest {
    static final String TEST_TYPE = 'API Error';
    static final String TEST_PROVIDER = 'DIRECTV';
    static final String TEST_PROVIDER_SUBTYPE = 'Beam';
    static final String TEST_TAB = 'Credit Check';
    static final String TEST_COMPONENT = 'API Error';
    static final String TEST_ERROR = 'Test Error Message';
    static final String TEST_ENDPOINT = 'creditCheck';
    static final String TEST_REQUEST = '{"partnerName": "directv"}';

    @TestSetup
    static void makeData() {
        Opportunity testOpportunity = new Opportunity(
            Name = 'test opportunity',
            StageName = 'Draft',
            CloseDate = Date.today()
        );
        insert testOpportunity;
    }

    @isTest
    static void logErrorTestPositive() {
        List<Error_Log__c> initialErrorLogs = [SELECT Id FROM Error_Log__c];
        Assert.isTrue(initialErrorLogs.isEmpty(), 'No Error_Log__c records should exist at beggining of the test');

        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        ErrorLogWrapper errorLogWrapper = new ErrorLogWrapper();
        errorLogWrapper.type = TEST_TYPE;
        errorLogWrapper.provider = TEST_PROVIDER;
        errorLogWrapper.providerSubtype = TEST_PROVIDER_SUBTYPE;
        errorLogWrapper.tab = TEST_TAB;
        errorLogWrapper.component = TEST_COMPONENT;
        errorLogWrapper.error = TEST_ERROR;
        errorLogWrapper.endpoint = TEST_ENDPOINT;
        errorLogWrapper.request = TEST_REQUEST;
        errorLogWrapper.opportunity = opp.Id;

        Test.startTest();
        ErrorLogModel.logError(errorLogWrapper);
        Test.stopTest();

        List<Error_Log__c> resultErrorLogs = [
            SELECT
                Id,
                Name,
                Type__c,
                Provider__c,
                Provider_Subtype__c,
                Tab__c,
                Component__c,
                Error__c,
                Endpoint__c,
                Request__c,
                Opportunity__c
            FROM Error_Log__c
        ];

        Assert.areEqual(1, resultErrorLogs.size(), 'An Error_Log__c record should have been created');
        Error_Log__c resultErrorLog = resultErrorLogs.get(0);

        Assert.areEqual(
            TEST_TYPE,
            resultErrorLog.Type__c,
            'Error_Log__c.Type__c field should match value passed in ErrorLogWrapper.type attribute'
        );
        Assert.areEqual(
            TEST_PROVIDER,
            resultErrorLog.Provider__c,
            'Error_Log__c.Provider__c field should match value passed in ErrorLogWrapper.provider attribute'
        );
        Assert.areEqual(
            TEST_PROVIDER_SUBTYPE,
            resultErrorLog.Provider_Subtype__c,
            'Error_Log__c.Provider_Subtype__c field should match value passed in ErrorLogWrapper.providerSubtype attribute'
        );
        Assert.areEqual(
            TEST_TAB,
            resultErrorLog.Tab__c,
            'Error_Log__c.Tab__c field should match value passed in ErrorLogWrapper.tab attribute'
        );
        Assert.areEqual(
            TEST_COMPONENT,
            resultErrorLog.Component__c,
            'Error_Log__c.Component__c field should match value passed in ErrorLogWrapper.component attribute'
        );
        Assert.areEqual(
            TEST_ERROR,
            resultErrorLog.Error__c,
            'Error_Log__c.Error__c field should match value passed in ErrorLogWrapper.error attribute'
        );
        Assert.areEqual(
            TEST_ENDPOINT,
            resultErrorLog.Endpoint__c,
            'Error_Log__c.Endpoint__c field should match value passed in ErrorLogWrapper.endpoint attribute'
        );
        Assert.areEqual(
            errorLogWrapper.request,
            resultErrorLog.Request__c,
            'Error_Log__c.Request__c field should match value passed in ErrorLogWrapper.request attribute'
        );
        Assert.areEqual(
            opp.Id,
            resultErrorLog.Opportunity__c,
            'Error_Log__c.Opportunity__c field should match value passed in ErrorLogWrapper.opportunity attribute'
        );
    }

    @isTest
    static void logErrorTestNegative() {
        List<Error_Log__c> initialErrorLogs = [SELECT Id FROM Error_Log__c];
        Assert.isTrue(initialErrorLogs.isEmpty(), 'No Error_Log__c records should exist at beggining of the test');

        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        ErrorLogWrapper errorLogWrapper = new ErrorLogWrapper();
        errorLogWrapper.provider = TEST_PROVIDER;
        errorLogWrapper.tab = TEST_TAB;

        Test.startTest();
        try {
            ErrorLogModel.logPublicError(errorLogWrapper);
        } catch (Exception exc) {
            System.debug(exc.getMessage());
        }
        Test.stopTest();

        List<Error_Log__c> resultErrorLogs = [
            SELECT
                Id,
                Name,
                Type__c,
                Provider__c,
                Tab__c,
                Component__c,
                Error__c,
                Endpoint__c,
                Request__c,
                Opportunity__c
            FROM Error_Log__c
        ];

        Assert.isTrue(resultErrorLogs.isEmpty(), 'No Error_Log__c records should be created');
    }

    @isTest
    static void logPublicErrorTest() {
        List<Error_Log__c> initialErrorLogs = [SELECT Id FROM Error_Log__c];
        Assert.isTrue(initialErrorLogs.isEmpty(), 'No Error_Log__c records should exist at beggining of the test');

        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        ErrorLogWrapper errorLog = new ErrorLogWrapper();
        errorLog.type = TEST_TYPE;
        errorLog.provider = TEST_PROVIDER;
        errorLog.providerSubtype = TEST_PROVIDER_SUBTYPE;
        errorLog.tab = TEST_TAB;
        errorLog.component = TEST_COMPONENT;
        errorLog.error = TEST_ERROR;
        errorLog.endpoint = TEST_ENDPOINT;
        errorLog.request = TEST_REQUEST;
        errorLog.opportunity = POE_PublicRecordAccessUtility.encryptRecordId(opp.Id);

        Test.startTest();
        ErrorLogModel.logPublicError(errorLog);
        Test.stopTest();

        List<Error_Log__c> resultErrorLogs = [
            SELECT Id
            FROM Error_Log__c
            WHERE Opportunity__c = :opp.Id
        ];
        Assert.areEqual(1, resultErrorLogs.size(), 'No error log was created with the decrypted Opportunity Id.');
    }
}