force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Object used to store error logs. (PER-2431)</description>
    <label>Chuzo Error Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chuzo Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <description>Name of the apex class or lightning web component in which the error occurred. (PER-2431)</description>
    <label>Component</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>If internal, this is the error message from the exception + the line number, if API call, then it is the response. (PER-2431)</description>
    <label>Error</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <description>Provider selected by the user in Chuzo. Leave empty if not applicable. (PER-2431)</description>
    <label>Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Determines if the error is coming from an API or if it is internal. (PER-2431)</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Error</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
            <value>
                <fullName>Lead Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FSL_DeleteDummyOrdersBatchTest.cls
@isTest
private class FSL_DeleteDummyOrdersBatchTest {
    private static final String GUEST_USER_NAME = 'SelfScheduleGuest';

    @testSetup
    static void makeData() {
        insert new FSL_Settings__c(Self_Schedule_Guest_User_Name__c = GUEST_USER_NAME);

        User guestUser = new User(
            LastName = GUEST_USER_NAME,
            Alias = 'guest',
            Email = 'FSL_DeleteDummyOrdersBatchTest' + DateTime.now().getTime() + '@hikko.com',
            UserName = 'FSL_DeleteDummyOrdersBatchTest' + DateTime.now().getTime() + '@hikko.com',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id,
            TimeZoneSidKey = 'America/Los_Angeles'
        );
        insert guestUser;

        System.runAs(guestUser) {
            insert new WorkOrder(
                Subject = 'Dummy Work Order',
                Status = 'New'
            );
        }
    }

    @isTest
    static void executeTest() {
        Test.startTest();
        Database.executeBatch(new FSL_DeleteDummyOrdersBatch(), 100);
        Test.stopTest();

        List<WorkOrder> workOrders = [SELECT Id FROM WorkOrder WHERE Subject = 'Dummy Work Order'];
        System.assertEquals(0, workOrders.size(), 'WorkOrder should have been deleted by the batch.');
    }

    @isTest
    static void testErrorHandling() {
        FSL_DeleteDummyOrdersBatch.throwException = true;

        Test.startTest();
        Database.executeBatch(new FSL_DeleteDummyOrdersBatch(), 100);
        Test.stopTest();

        List<Error_Log__c> errorLogs = [
            SELECT  Id, Type__c, Provider__c, Component__c, Error__c, CreatedDate
            FROM    Error_Log__c
            WHERE   Component__c = 'FSL_DeleteDummyOrdersBatch'
        ];

        Assert.areEqual(1, errorLogs.size(), 'Should have created an error log.');
    }
}