force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Object used to store error logs. (PER-2431)</description>
    <label>Chuzo Error Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chuzo Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>If internal, this is the error message from the exception + the line number, if API call, then it is the response. (PER-2431)</description>
    <label>Error</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/POE_ConciergeLeadCreationQueueableTest.cls
@isTest
public class POE_ConciergeLeadCreationQueueableTest {
    public static final String EXTERNAL_LEAD_ID = 'testleadid';

    @TestSetup
    static void setup() {
        Lead testLead = TestHelper.getLeads(1)[0];
        insert testLead;
    }
    
    @isTest
    static void conciergeLeadCreationQueueableSuccessTest() {
        Lead testLead = [SELECT Id FROM Lead LIMIT 1]; 

        Test.setMock(HttpCalloutMock.class, new POE_ConciergeLeadCreationCalloutMock(true));
        Test.startTest();
        System.enqueueJob(new POE_ConciergeLeadCreationQueueable(testLead.Id));
        Test.stopTest();

        Lead updatedLead = [
            SELECT Id, Concierge_External_Id__c
            FROM Lead
            WHERE Id = :testLead.Id
        ];
        Assert.isTrue(
            String.isNotBlank(updatedLead.Concierge_External_Id__c),
            'The Concierge External Id field was not set when the callout was successful'
        );
    }

    @isTest
    static void conciergeLeadCreationQueueableFailureTest() {
        Lead testLead = [SELECT Id FROM Lead LIMIT 1]; 

        Test.setMock(HttpCalloutMock.class, new POE_ConciergeLeadCreationCalloutMock(false));
        Test.startTest();
        System.enqueueJob(new POE_ConciergeLeadCreationQueueable(testLead.Id));
        Test.stopTest();

        Lead updatedLead = [
            SELECT Id, Concierge_External_Id__c
            FROM Lead
            WHERE Id = :testLead.Id
        ];
        Assert.isTrue(
            String.isBlank(updatedLead.Concierge_External_Id__c),
            'The Concierge External Id field was set when the callout failed'
        );

        List<Error_Log__c> errorLogList = [
            SELECT Id, Error__c
            FROM Error_Log__c
        ];
        Boolean errorLogExists = false;
        for (Error_Log__c errorLog : errorLogList) {
            errorLogExists = errorLog.Error__c == POE_ConciergeLeadCreationCalloutMock.ERROR_MESSAGE
                             || errorLogExists;
        }

        Assert.isTrue(
            errorLogExists,
            'No error was created with the error message from the response'
        );
    }
}