force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Object used to store error logs. (PER-2431)</description>
    <label>Chuzo Error Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chuzo Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <description>Name of the apex class or lightning web component in which the error occurred. (PER-2431)</description>
    <label>Component</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>The endpoint that is failing, is only applicable if the type is ‘API Error’. (PER-2431)</description>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>If internal, this is the error message from the exception + the line number, if API call, then it is the response. (PER-2431)</description>
    <label>Error</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to the buyflow that failed. (PER-2431)</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <description>Provider selected by the user in Chuzo. Leave empty if not applicable. (PER-2431)</description>
    <label>Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Provider_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Provider_Subtype__c</fullName>
    <label>Provider Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beam</fullName>
            </value>
            <value>
                <fullName>Stream</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>The request for the API call, is only applicable if the type is ‘API Error’. (PER-2431)</description>
    <label>Request</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Tab__c.field-meta.xml
<CustomField>
    <fullName>Tab__c</fullName>
    <description>Tab in which the error occurred in Chuzo. Leave empty if not applicable. (PER-2431)</description>
    <label>Tab</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Determines if the error is coming from an API or if it is internal. (PER-2431)</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Error</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
            <value>
                <fullName>Lead Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ErrorLogModel.cls
public without sharing class ErrorLogModel {
    @AuraEnabled
    public static Error_Log__c logError(ErrorLogWrapper error) {
        Error_Log__c errorLog = new Error_Log__c();

        try {
            errorLog.Type__c = error.type != null ? error.type : null;
            errorLog.Provider__c = error.provider != null ? error.provider : null;
            errorLog.Provider_Subtype__c = error.providerSubtype != null ? error.providerSubtype : null;
            errorLog.Tab__c = error.tab != null ? error.tab : null;
            errorLog.Component__c = error.component != null ? error.component : null;
            errorLog.Error__c = error.error != null ? error.error : null;
            errorLog.Endpoint__c = error.endpoint != null ? error.endpoint : null;
            errorLog.Request__c = error.request != null ? error.request : null;
            errorLog.Opportunity__c = error.opportunity != null ? error.opportunity : null;

            insert errorLog;

            return errorLog;
        } catch (Exception exc) {
            throw new AuraHandledException(exc.getMessage());
        }
    }

    @AuraEnabled
    public static Error_Log__c logPublicError(ErrorLogWrapper error) {
        String decryptedOppId = error.opportunity;
        try {
            decryptedOppId = POE_PublicRecordAccessUtility.decryptRecordId(error.opportunity);
        } catch (Exception e) {
            decryptedOppId = null;
        }

        error.opportunity = decryptedOppId;
        return ErrorLogModel.logError(error);
    }
}