force-app/main/default/objects/Work_Type_SR_Count__c/Work_Type_SR_Count__c.object-meta.xml
<CustomObject>
    <label>Work Type SR Count</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Work Type SR Count Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Type SR Counts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Type_SR_Count__c/fields/No_of_skilled_resources__c.field-meta.xml
<CustomField>
    <fullName>No_of_skilled_resources__c</fullName>
    <label>No. of skilled resources</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Type_SR_Count__c/fields/Service_Resource_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource_Percentage__c</fullName>
    <label>Service Resource Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Work_Type_SR_Count__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Work Type SR Counts</relationshipLabel>
    <relationshipName>Work_Type_SR_Counts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Type_SR_Count__c/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Type</label>
    <referenceTo>WorkType</referenceTo>
    <relationshipLabel>Work Type SR Counts</relationshipLabel>
    <relationshipName>Work_Type_SR_Counts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PV_UpdatePercentInWTSRBatch.cls
global class PV_UpdatePercentInWTSRBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Service_Territory__r.ParentTerritoryId, Work_Type__c, No_of_skilled_resources__c, Service_Resource_Percentage__c FROM Work_Type_SR_Count__c';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bC, List<Work_Type_SR_Count__c> wtsrList) {
        PV_WorkTypeSRCountHandler.updatePercentageInWTSRCount(wtsrList);
    }
    
    global void finish(Database.BatchableContext bC) {
    }
}