force-app/main/default/objects/Work_Type_SR_Count__c/Work_Type_SR_Count__c.object-meta.xml
<CustomObject>
    <label>Work Type SR Count</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Work Type SR Count Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Type SR Counts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Type_SR_Count__c/fields/No_of_skilled_resources__c.field-meta.xml
<CustomField>
    <fullName>No_of_skilled_resources__c</fullName>
    <label>No. of skilled resources</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Type_SR_Count__c/fields/Service_Resource_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource_Percentage__c</fullName>
    <label>Service Resource Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Work_Type_SR_Count__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Work Type SR Counts</relationshipLabel>
    <relationshipName>Work_Type_SR_Counts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Type_SR_Count__c/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Type</label>
    <referenceTo>WorkType</referenceTo>
    <relationshipLabel>Work Type SR Counts</relationshipLabel>
    <relationshipName>Work_Type_SR_Counts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PV_WorkTypeSRCountHandler.cls
public class PV_WorkTypeSRCountHandler {

    public static void updatePercentageInWTSRCount(List<Work_Type_SR_Count__c> wtsrList) {
        Map<Id, Map<Id, Integer>> territoryWorkTypeMap = new Map<Id, Map<Id, Integer>>();
        List<Work_Type_SR_Count__c> wtSrCountUpdateList = new List<Work_Type_SR_Count__c>();
        Set<id> parentTerritorySet = new Set<Id>();

        for (Work_Type_SR_Count__c wtsr : wtsrList) {
            parentTerritorySet.add(wtsr.Service_Territory__r.ParentTerritoryId);
        }

        AggregateResult[] groupedResults = [
            SELECT  Count(Id), Sum(No_of_skilled_resources__c) skilledResources, Service_Territory__r.ParentTerritoryId parentTerritory,Work_Type__c worktypeId 
            FROM    Work_Type_SR_Count__c 
            WHERE   Service_Territory__r.ParentTerritoryId IN : parentTerritorySet 
            GROUP BY Service_Territory__r.ParentTerritoryId ,Work_Type__c
        ];
                                           
        for (AggregateResult agr:groupedResults) {
            if (!territoryWorkTypeMap.containsKey((Id)agr.get('parentTerritory'))) {
                territoryWorkTypeMap.put((Id)agr.get('parentTerritory'), new Map<Id, Integer>{(Id)agr.get('worktypeId') =>  Integer.valueOf(agr.get('skilledResources'))});    
            } else {
                territoryWorkTypeMap.get((Id)agr.get('parentTerritory')).put((Id)agr.get('worktypeId'), Integer.valueOf(agr.get('skilledResources')));
            }
        }

        for (Work_Type_SR_Count__c wtsr : wtsrList) {
            if (territoryWorkTypeMap.containsKey(wtsr.Service_Territory__r.ParentTerritoryId) && 
               territoryWorkTypeMap.get(wtsr.Service_Territory__r.ParentTerritoryId).containsKey(wtsr.Work_Type__c))
            {
                wtsr.Service_Resource_Percentage__c = (wtsr.No_of_skilled_resources__c / territoryWorkTypeMap.get(wtsr.Service_Territory__r.ParentTerritoryId).get(wtsr.Work_Type__c))*100;
                wtSrCountUpdateList.add(wtsr);
            }
        }

        if (!wtSrCountUpdateList.isEmpty()) {
            Database.update(wtSrCountUpdateList, true, AccessLevel.SYSTEM_MODE);
        }
    }

    @InvocableMethod(label='Handle Territory Inactivation' description='Handles the inactivation of a territory')
    public static void handleTerritoryInactivation(List<Id> territoryIds) {
        Set<Id> parentTerritoryIds = new Set<Id>();
        
        for (ServiceTerritory serviceTerritory : [SELECT ParentTerritoryId FROM ServiceTerritory WHERE Id = :territoryIds]) {
            if (serviceTerritory.ParentTerritoryId != null) {
                parentTerritoryIds.add(serviceTerritory.ParentTerritoryId);
            }
        }

        List<Work_Type_SR_Count__c> wtsrList = [
            SELECT  Id, Service_Territory__r.ParentTerritoryId, Work_Type__c, No_of_skilled_resources__c, Service_Resource_Percentage__c
            FROM    Work_Type_SR_Count__c
            WHERE   Service_Territory__r.ParentTerritoryId IN :parentTerritoryIds
        ];
        
        updatePercentageInWTSRCount(wtsrList);
    }
}