force-app/main/default/objects/Custom_Charge__c/Custom_Charge__c.object-meta.xml
<CustomObject>
    <label>Custom Charge</label>
    <nameField>
        <displayFormat>PV-CP-{0000000}</displayFormat>
        <label>Custom Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Charge__c/fields/Allow_Override_Price__c.field-meta.xml
<CustomField>
    <fullName>Allow_Override_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PVFSL-266</description>
    <inlineHelpText>When this is checked users in the mobile app can manually update the price.</inlineHelpText>
    <label>Allow Override Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Charge__c/fields/CustomCharge_Products__c.field-meta.xml
<CustomField>
    <fullName>CustomCharge_Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CustomCharge_Products</label>
    <referenceTo>CustomCharge_Products__c</referenceTo>
    <relationshipLabel>Custom Charges</relationshipLabel>
    <relationshipName>Custom_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Charge__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Custom Charges</relationshipLabel>
    <relationshipName>Custom_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Charge__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FSL_Vendors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomCharge_Products__c/CustomCharge_Products__c.object-meta.xml
<CustomObject>
    <label>CustomCharge_Products</label>
    <nameField>
        <label>CustomCharge_Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomCharge_Productss</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomCharge_Products__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <description>This field represents to which FSL vendor this product belongs to. Only dealers with the vendor assigned will be able to see this product. (PVFSL-354)</description>
    <inlineHelpText>This field represents to which FSL vendor this product belongs to. Only dealers with the vendor assigned will be able to see this product.</inlineHelpText>
    <label>Vendor</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FSL_Vendors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/PV_CustomChargeController.cls
public with sharing class PV_CustomChargeController {
    
    @AuraEnabled(cacheable=true)
    public static FSL_AppUtils.ResponseWrapper getAllProducts() {
        
        try {
            
            Map<String, List<CustomCharge_Products__c>> productMap = new Map<String, List<CustomCharge_Products__c>>();

            for (CustomCharge_Products__c product : [SELECT Name, Id, Price__c, Vendor__c FROM CustomCharge_Products__c]) {
                if (!productMap.containsKey(product.Vendor__c)) {
                    productMap.put(product.Vendor__c, new List<CustomCharge_Products__c>());
                }
                productMap.get(product.Vendor__c).add(product);
            }
    
            return new FSL_AppUtils.ResponseWrapper('SUCCESS', productMap, null);
            
        }catch(Exception e) {
            return new FSL_AppUtils.ResponseWrapper('ERROR', null, e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static FSL_AppUtils.ResponseWrapper getProductPrice() {

        try {
            return new FSL_AppUtils.ResponseWrapper('SUCCESS', [SELECT Id, Name, Price__c FROM CustomCharge_Products__c], null);
        }catch(Exception e) {
            return new FSL_AppUtils.ResponseWrapper('ERROR', null, e.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<Custom_Charge__c> getCustomCharge(String saId) {
        return [
            SELECT  Id, Quantity__c, Price__c, Total_Amount__c, Vendor__c, Allow_Override_Price__c
            FROM    Custom_Charge__c
            WHERE   Service_Appointment__c = :saId
        ];
    }
    
    @AuraEnabled
    public static List<ServiceAppointment> getSAAmount(String saId) {
        return [SELECT Id, Total_Amount__c FROM ServiceAppointment WHERE Id = :saId];
    }

    @AuraEnabled
    public static FSL_AppUtils.ResponseWrapper getVendors(Id serviceAppointmentId) {

        try {

            List<VendorValue> result = new List<VendorValue>();
        
            ServiceAppointment serviceAppointment = [
                SELECT  Dealer__r.Available_FSL_Vendors__c 
                FROM    ServiceAppointment 
                WHERE   Id = :serviceAppointmentId
                LIMIT 1
            ];
            
            if (serviceAppointment.Dealer__r != null && String.isNotBlank(serviceAppointment.Dealer__r.Available_FSL_Vendors__c)) {
                List<String> values = serviceAppointment.Dealer__r.Available_FSL_Vendors__c.split(';');
                
                for (String value : values) {
                    VendorValue newVendor = new VendorValue();
                    newVendor.label = newVendor.value = value;
                    result.add(newVendor);
                }
            } else {
                throw new AuraHandledException('The service appointment is not assigned to an FSL Dealer.');
            }

            return new FSL_AppUtils.ResponseWrapper('SUCCESS', result, null);

        }catch(Exception e) {
            return new FSL_AppUtils.ResponseWrapper('ERROR', null, e.getMessage());
        }
    }

    public class VendorValue {
        @AuraEnabled
        public String label {get; set;}
        @AuraEnabled
        public String value {get; set;}
    }
    
}