force-app/main/default/objects/POE_ClientProduct__c/POE_ClientProduct__c.object-meta.xml
<CustomObject>
    <label>Client Product</label>
    <nameField>
        <label>Client Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POE_ClientProduct__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE_ClientProduct__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/POE_ClientProduct__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Program</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/POEUpsertClientProduct.cls
global without sharing class POEUpsertClientProduct implements vlocity_cmt.VlocityOpenInterface {
    global Boolean invokeMethod(
        String methodName,
        Map<String, Object> inputMap,
        Map<String, Object> outMap,
        Map<String, Object> options
    ) {
        Boolean result = true;
        try {
            String productName = (String) inputMap.get('Name');
            List<POE_ClientProduct__c> prods = [SELECT Id, Name FROM POE_ClientProduct__c WHERE Name = :productName];
            if (prods.isEmpty()) {
                POE_ClientProduct__c prod = new POE_ClientProduct__c();
                prod.Name = productName;
                prod.Unit_Price__c = (Decimal) inputMap.get('UnitPrice');
                prod.Code__c = (String) inputMap.get('Code');
                prod.Family__c = (String) inputMap.get('Family');
                prod.Description__c = (String) inputMap.get('Description');
                insert prod;
                outMap.put('ProductName', prod.Name);
            } else {
                List<POE_ClientProduct__c> updateOp = new List<POE_ClientProduct__c>();
                for (POE_ClientProduct__c pr : prods) {
                    pr.Unit_Price__c = (Decimal) inputMap.get('UnitPrice');
                    pr.Description__c = (String) inputMap.get('Description');
                    updateOp.add(pr);
                    outMap.put('ProductName', pr.Name);
                }
                update updateOp;
            }
        } catch (Exception e) {
            result = false;
        }
        return result;
    }
}