force-app/main/default/objects/DealerMDU__c/DealerMDU__c.object-meta.xml
<CustomObject>
    <label>DealerMDU</label>
    <nameField>
        <label>DealerMDU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DealerMDUs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DealerMDU__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Dealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DealerMDUs</relationshipLabel>
    <relationshipName>DealerMDUs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DealerMDU__c/fields/MDU_Chuzo__c.field-meta.xml
<CustomField>
    <fullName>MDU_Chuzo__c</fullName>
    <label>MDU Chuzo</label>
    <referenceTo>MDU_Chuzo__c</referenceTo>
    <relationshipLabel>DealerMDUs</relationshipLabel>
    <relationshipName>DealerMDUs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MDU_Chuzo__c/MDU_Chuzo__c.object-meta.xml
<CustomObject>
    <label>MDU Chuzo</label>
    <nameField>
        <label>MDU Chuzo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDUs Chuzo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MDU_Chuzo__c/fields/DIRECTV_Dealer_Code_FFL__c.field-meta.xml
<CustomField>
    <fullName>DIRECTV_Dealer_Code_FFL__c</fullName>
    <label>DIRECTV Dealer Code FFL</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDU_Chuzo__c/fields/DIRECTV_Dealer_Code_NFFL__c.field-meta.xml
<CustomField>
    <fullName>DIRECTV_Dealer_Code_NFFL__c</fullName>
    <label>DIRECTV Dealer Code NFFL</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE_DealerEvent__c/POE_DealerEvent__c.object-meta.xml
<CustomObject>
    <label>DealerEvent</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>DealerEvent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DealerEvents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/POE_DealerEvent__c/fields/POE_Dealer__c.field-meta.xml
<CustomField>
    <fullName>POE_Dealer__c</fullName>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Events</relationshipLabel>
    <relationshipName>DealerEvents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/POE_DealerEvent__c/fields/POE_Event__c.field-meta.xml
<CustomField>
    <fullName>POE_Event__c</fullName>
    <label>Event</label>
    <referenceTo>POE_Event__c</referenceTo>
    <relationshipLabel>DealerEvents</relationshipLabel>
    <relationshipName>DealerEvents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/POE_DealerStore__c/POE_DealerStore__c.object-meta.xml
<CustomObject>
    <label>DealerStore</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>DealerStore Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DealerStores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/POE_DealerStore__c/fields/POE_Dealer__c.field-meta.xml
<CustomField>
    <fullName>POE_Dealer__c</fullName>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Stores</relationshipLabel>
    <relationshipName>DealerStores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/POE_DealerStore__c/fields/POE_End_Date__c.field-meta.xml
<CustomField>
    <fullName>POE_End_Date__c</fullName>
    <description>The date when the dealer&apos;s association with the retail store ended.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/POE_DealerStore__c/fields/POE_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>POE_Start_Date__c</fullName>
    <description>The date when the dealer started association with the retail store. (PER-3205)</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/POE_DealerStore__c/fields/POE_Store__c.field-meta.xml
<CustomField>
    <fullName>POE_Store__c</fullName>
    <label>Store</label>
    <referenceTo>POE_Retail_Store__c</referenceTo>
    <relationshipLabel>DealerStores</relationshipLabel>
    <relationshipName>DealerStores</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/POE_Event__c/POE_Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POE_Event__c/fields/POE_City__c.field-meta.xml
<CustomField>
    <fullName>POE_City__c</fullName>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE_Event__c/fields/POE_State__c.field-meta.xml
<CustomField>
    <fullName>POE_State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/POE_Event__c/fields/POE_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>POE_Street_Address__c</fullName>
    <label>Street Address</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE_Event__c/fields/POE_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>POE_Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE_Retail_Store__c/POE_Retail_Store__c.object-meta.xml
<CustomObject>
    <label>Retail Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POE_Retail_Store__c/fields/POE_End_Date__c.field-meta.xml
<CustomField>
    <fullName>POE_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/POE_Retail_Store__c/fields/POE_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>POE_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/POE_Retail_Store__c/fields/POE_State__c.field-meta.xml
<CustomField>
    <fullName>POE_State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClickerControllerTest.cls
@isTest
public class ClickerControllerTest {
    @TestSetup
    static void makeData() {
        UserRole userRole = [SELECT Id, DeveloperName FROM UserRole WHERE DeveloperName = 'Sales_Supervisor' LIMIT 1];
        User adminUser = [SELECT Id, UserRoleId FROM User WHERE Profile.Name = 'System Administrator' LIMIT 1];
        adminUser.UserRoleId = userRole.Id;
        adminUser.isActive = true;
        update adminUser;
        RecordType rtype = [
            SELECT Name, Id
            FROM RecordType
            WHERE sObjectType = 'Account' AND Name = 'Dealer' AND isActive = TRUE
            LIMIT 1
        ];

        System.runAs(adminUser) {
            Account testAcc = new Account(
                Name = 'Test Account',
                ShippingStreet = 'Test Street',
                POE_Dealer_Office_Email__c = 'DealerEmail@testorg1.com',
                P10_Invoice_Account__c = 'Example',
                recordTypeId = rtype.Id
            );
            insert testAcc;

            Contact userContact = new Contact(FirstName = 'test', LastName = 'test', AccountId = testAcc.Id);
            insert userContact;

            Profile p = TestHelper.getGeneralProfile();
            User u = new User(
                Alias = 'standt',
                Email = '11052022standarduser@testorg.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Testing',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = p.Id,
                ContactId = userContact.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = '11052022GDGstandarduser@testorg.com'
            );
            insert u;
        }
    }
    
    @isTest
    static void testGetClickerCallCenterTrack() {
        List<User> user = [SELECT Id, AccountId FROM User WHERE LastName = 'Testing' LIMIT 1];
        
        test.startTest();
        Map<String, Object> result = ClickerController.getClickerCallCenterTrack(user[0].Id, null);
        System.debug('result:   '+result);
        test.stopTest();
        System.assert(result != null, 'Call Center Track is Null');
    }

    @isTest
    static void testGetStoreSuccess() {
        POE_Retail_Store__c retailStore = new POE_Retail_Store__c(
            Name = 'Test Store',
            POE_City__c = 'San Francisco',
            POE_State__c = 'California',
            POE_Street_Address__c = '416 Mission Street',
            POE_Zip_Code__c = '94103'
        );
        insert retailStore;

        List<User> user = [SELECT Id, AccountId FROM User WHERE LastName = 'Testing' LIMIT 1];
        POE_DealerStore__c dealerStore = new POE_DealerStore__c(
            POE_Dealer__c = user[0].AccountId,
            POE_Store__c = retailStore.Id,
            POE_Start_Date__c = Date.today().addDays(-1),
            POE_End_Date__c = null
        );
        insert dealerStore;

        System.runAs(user[0]) {
            Test.startTest();
            Map<String, Object> result = ClickerController.getStore();
            Test.stopTest();
            Assert.areEqual(user[0].Id, ((User) result.get('User'))?.Id, 'User Id does not match');
            Assert.areEqual(user[0].AccountId, ((Id) result.get('Account')), 'Account does not match');
            Assert.areEqual(
                dealerStore.Id,
                ((List<POE_DealerStore__c>) result.get('DealerStore'))[0]?.Id,
                'DealerStore does not match'
            );
        }
    }

    @isTest
    static void testGetStoreRetailStoreFail() {
        List<User> user = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
        System.runAs(user[0]) {
            Test.startTest();
            Map<String, Object> result = ClickerController.getStore();
            Test.stopTest();
            Assert.areEqual('No Dealer Stores found', result.get('error'), 'Error does not match');
        }
    }

    @isTest
    static void testGetEventSuccess() {
        POE_Event__c event = new POE_Event__c(
            Name = 'Test Event',
            POE_City__c = 'San Francisco',
            POE_State__c = 'California',
            POE_Street_Address__c = '416 Mission Street',
            POE_Zip_Code__c = '94103'
        );
        insert event;

        List<User> user = [SELECT Id, AccountId FROM User WHERE LastName = 'Testing' LIMIT 1];
        POE_DealerEvent__c dealerEvent = new POE_DealerEvent__c(
            POE_Dealer__c = user[0].AccountId,
            POE_Event__c = event.Id
        );
        insert dealerEvent;

        System.runAs(user[0]) {
            Test.startTest();
            Map<String, Object> result = ClickerController.getEvent();
            Test.stopTest();

            Assert.areEqual(user[0].Id, ((User) result.get('User'))?.Id, 'User Id does not match');
            Assert.areEqual(user[0].AccountId, ((Id) result.get('Account')), 'Account does not match');
            Assert.areEqual(
                dealerEvent.Id,
                ((List<POE_DealerEvent__c>) result.get('DealerEvent'))[0]?.Id,
                'DealerEvent does not match'
            );
        }
    }

    @isTest
    static void testGetEventDealerEventFail() {
        List<User> user = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
        System.runAs(user[0]) {
            Test.startTest();
            Map<String, Object> result = ClickerController.getEvent();
            Test.stopTest();
            Assert.areEqual('No Dealer Events found', result.get('error'), 'Error does not match');
        }
    }
    @isTest
    static void testLogAnInteractionStore() {
        POE_Retail_Store__c retailStore = new POE_Retail_Store__c(
            Name = 'Test Store',
            POE_City__c = 'San Francisco',
            POE_State__c = 'California',
            POE_Street_Address__c = '416 Mission Street',
            POE_Zip_Code__c = '94103'
        );
        insert retailStore;
        List<User> user = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];

        System.runAs(user[0]) {
            Id clickerLocationRecordType = ClickerController.getClickerLocationRecordType();
            maps__Location__c geoLocation = new maps__Location__c(
                RecordTypeId = clickerLocationRecordType,
                Name = 'Test Location',
                maps__Latitude__c = 0.0,
                maps__Longitude__c = 0.0
            );
            insert geoLocation;
            Test.startTest();
            Map<String, Object> result = ClickerController.logAnInteraction('retail', user[0].Id, retailStore.Id);
            Test.stopTest();
            Assert.areEqual(false, result.get('error'), 'Triggered an error');
            Assert.areEqual(1, result.get('countContact'), 'Counter should be 1');
        }
    }

    @isTest
    static void testLogAnInteractionEvent() {
        POE_Event__c event = new POE_Event__c(
            Name = 'Test Event',
            POE_City__c = 'San Francisco',
            POE_State__c = 'California',
            POE_Street_Address__c = '416 Mission Street',
            POE_Zip_Code__c = '94103'
        );
        insert event;
        List<User> user = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];

        System.runAs(user[0]) {
            Id clickerLocationRecordType = ClickerController.getClickerLocationRecordType();
            maps__Location__c geoLocation = new maps__Location__c(
                RecordTypeId = clickerLocationRecordType,
                Name = 'Test Location',
                maps__Latitude__c = 0.0,
                maps__Longitude__c = 0.0
            );
            insert geoLocation;
            Test.startTest();
            Map<String, Object> result = ClickerController.logAnInteraction('event', user[0].Id, event.Id);
            Test.stopTest();
            Assert.areEqual(false, result.get('error'), 'Triggered an error');
            Assert.areEqual(1, result.get('countContact'), 'Counter should be 1');
        }
    }

    @isTest
    static void testGetUserFraudFlag() {
        User testUser = [SELECT Id, POE_FraudObservation__c FROM User WHERE LastName = 'Testing' LIMIT 1];
        testUser.POE_FraudObservation__c = true;
        update testUser;

        System.runAs(testUser) {
            Test.startTest();
            Boolean isFraud = ClickerController.getUserFraudFlag(testUser.Id);
            Test.stopTest();
            Assert.isTrue(isFraud, 'Expected fraud flag to be true');
        }

    }

    @isTest
    static void testGetMDUSuccess() {
        MDU_Chuzo__c mdu = new MDU_Chuzo__c(
            Name = 'Test MDU'
        );
        insert mdu;

        List<User> user = [SELECT Id, AccountId FROM User WHERE LastName = 'Testing' LIMIT 1];
        DealerMDU__c dealerMDU = new DealerMDU__c(
            Dealer__c = user[0].AccountId,
            MDU_Chuzo__c = mdu.Id
        );
        insert dealerMDU;

        System.runAs(user[0]) {
            Test.startTest();
            Map<String, Object> result = ClickerController.getMDU();
            Test.stopTest();
            Assert.areEqual(user[0].Id, ((User) result.get('User'))?.Id, 'User Id does not match');
            Assert.areEqual(user[0].AccountId, ((Id) result.get('Account')), 'Account does not match');
            Assert.areEqual(
                dealerMDU.Id,
                ((List<DealerMDU__c>) result.get('DealerMDU'))[0]?.Id,
                'DealerMDU does not match'
            );
        }
    }

    @isTest
    static void testGetMDUDealerMDUFail() {
        List<User> user = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
        System.runAs(user[0]) {
            Test.startTest();
            Map<String, Object> result = ClickerController.getMDU();
            Test.stopTest();
            Assert.areEqual('No Dealer MDUs found', result.get('error'), 'Error does not match');
        }
    }

    @isTest
    static void testGetClickerMDUTrack() {
        MDU_Chuzo__c mdu = new MDU_Chuzo__c(
            Name = 'Test MDU',
            DIRECTV_Dealer_Code_FFL__c = 'FFL123',
            DIRECTV_Dealer_Code_NFFL__c = 'NFFL456'
        );
        insert mdu;

        List<User> user = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
        
        System.runAs(user[0]) {
            Test.startTest();
            Map<String, Object> result = ClickerController.getClickerMDUTrack(user[0].Id, null);
            Test.stopTest();
            System.assert(result != null, 'MDU Track is Null');
            Assert.areEqual(0, result.get('countContact'), 'Contact count should be 0');
            Assert.areEqual(0, result.get('countServiceability'), 'Serviceability count should be 0');
            Assert.areEqual(0, result.get('countProduct'), 'Product count should be 0');
            Assert.areEqual(0, result.get('countCompleted'), 'Completed count should be 0');
        }
    }

    @isTest
    static void testLogAnInteractionMDU() {
        MDU_Chuzo__c mdu = new MDU_Chuzo__c(
            Name = 'Test MDU'
        );
        insert mdu;
        List<User> user = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];

        System.runAs(user[0]) {
            Id clickerLocationRecordType = ClickerController.getClickerLocationRecordType();
            maps__Location__c geoLocation = new maps__Location__c(
                RecordTypeId = clickerLocationRecordType,
                Name = 'Test Location',
                maps__Latitude__c = 0.0,
                maps__Longitude__c = 0.0
            );
            insert geoLocation;
            Test.startTest();
            Map<String, Object> result = ClickerController.logAnInteraction('mdu', user[0].Id, mdu.Id);
            Test.stopTest();
            Assert.areEqual(false, result.get('error'), 'Triggered an error');
            Assert.areEqual(1, result.get('countContact'), 'Counter should be 1');
        }
    }
}