force-app/main/default/objects/Chuzo_Creditcard_Encryption_Key__mdt/Chuzo_Creditcard_Encryption_Key__mdt.object-meta.xml
<CustomObject>
    <description>Stores the AES256 used to encrypt/decrypt PCI Form Creditcards. [PER-3161]</description>
    <label>Chuzo Creditcard Encryption Key</label>
    <pluralLabel>Chuzo Creditcard Encryption Keys</pluralLabel>
</CustomObject>

force-app/main/default/objects/Chuzo_Creditcard_Encryption_Key__mdt/fields/key__c.field-meta.xml
<CustomField>
    <fullName>key__c</fullName>
    <description>Encryption Key</description>
    <label>key</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/POE_CCEncryptionKeyGenerationSchedulable.cls
global class POE_CCEncryptionKeyGenerationSchedulable implements Schedulable {
    public void execute(SchedulableContext SC) {
        String metadataName = 'CC_Encryption_Key';
        String metadataLabel = 'CC Encryption Key';
        String customMetadataTypeName = 'Chuzo_Creditcard_Encryption_Key__mdt';
        String metadataKeyField = 'key__c';

        POE_CustomMetadataService deployService = new POE_CustomMetadataService();

        Boolean updateMetadata = deployService.updateAndDeployMetadata(
            metadataName,
            metadataLabel,
            customMetadataTypeName,
            metadataKeyField
        );
    }
}