force-app/main/default/objects/POE_ACI_Statistic__c/POE_ACI_Statistic__c.object-meta.xml
<CustomObject>
    <description>Captures the ACI Statistics.</description>
    <label>ACI Statistic</label>
    <nameField>
        <displayFormat>ACI#{YYYY}{MM}-{00000000}</displayFormat>
        <label>ACI Statistic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACI Statistics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POE_ACI_Statistic__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>ACI Statistics</relationshipLabel>
    <relationshipName>ACI_Statistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/POE_ACI_Statistic__c/fields/Order_Created__c.field-meta.xml
<CustomField>
    <fullName>Order_Created__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order Created</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/POE_ACI_Statistic__c/fields/Presentation__c.field-meta.xml
<CustomField>
    <fullName>Presentation__c</fullName>
    <defaultValue>0</defaultValue>
    <label>DM</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/POE_Clicker_Event_Track__c/fields/POE_Event__c.field-meta.xml
<CustomField>
    <fullName>POE_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>POE_Event__c</referenceTo>
    <relationshipLabel>Clicker Store Tracks</relationshipLabel>
    <relationshipName>Clicker_Store_Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/POE_Clicker_Retail_Track__c/fields/POE_Store__c.field-meta.xml
<CustomField>
    <fullName>POE_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>POE_Retail_Store__c</referenceTo>
    <relationshipLabel>Clicker Retail Tracks</relationshipLabel>
    <relationshipName>Clicker_Retail_Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/POE_Event__c/POE_Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POE_Event__c/fields/POE_City__c.field-meta.xml
<CustomField>
    <fullName>POE_City__c</fullName>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE_Event__c/fields/POE_State__c.field-meta.xml
<CustomField>
    <fullName>POE_State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/POE_Event__c/fields/POE_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>POE_Street_Address__c</fullName>
    <label>Street Address</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE_Event__c/fields/POE_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>POE_Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE_Retail_Store__c/POE_Retail_Store__c.object-meta.xml
<CustomObject>
    <label>Retail Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POE_Retail_Store__c/fields/POE_State__c.field-meta.xml
<CustomField>
    <fullName>POE_State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/POE_SaveACIStatisticsTest.cls
@isTest
public with sharing class POE_SaveACIStatisticsTest {
    @TestSetup
    static void makeData() {
        POE_Retail_Store__c store = new POE_Retail_Store__c();
        store.Name = 'Test Store';
        store.Location__latitude__s = 34.000;
        store.Location__longitude__s = 50.000;
        store.POE_City__c = 'San Francisco';
        store.POE_State__c = 'California';
        store.POE_Street_Address__c = 'Test Street';
        store.POE_Zip_Code__c = '94105';
        insert store;

        POE_Clicker_Retail_Track__c track = new POE_Clicker_Retail_Track__c();
        track.POE_Store__c = store.Id;
        insert track;

        POE_Event__c event = new POE_Event__c();
        event.Name = 'Test Store';
        event.Location__latitude__s = 34.000;
        event.Location__longitude__s = 50.000;
        event.POE_City__c = 'San Francisco';
        event.POE_State__c = 'California';
        event.POE_Street_Address__c = 'Test Street';
        event.POE_Zip_Code__c = '94105';
        insert event;

        POE_Clicker_Event_Track__c track2 = new POE_Clicker_Event_Track__c();
        track2.POE_Event__c = event.Id;
        insert track2;

        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;

        Opportunity opp = new Opportunity();
        opp.CloseDate = System.today();
        opp.Name = 'Test Opportunity';
        opp.Maps_Latitude__c = 50.11;
        opp.Maps_Longitude__c = 30.33;
        opp.AccountId = acc.Id;
        opp.StageName = 'Opportunity';
        opp.Maps_PostalCode__c = '72212';
        insert opp;
    }

    @isTest
    private static void testInitialSave() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        List<Order> ord = new List<Order>();
        Test.startTest();
        POE_SaveACIStatistics.initialSave(opp.Id, 34.000, 50.000);
        ord = POE_SaveACIStatistics.getData(opp.Id);
        Test.stopTest();
        List<POE_ACI_Statistic__c> aci = [
            SELECT Id, Order_Created__c
            FROM POE_ACI_Statistic__c
            WHERE Opportunity__c = :opp.Id
        ];
        System.assertEquals(1, aci.size(), 'ACI not inserted');
    }

    @isTest
    private static void testInitialSaveWithPreviousACI() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        POE_ACI_Statistic__c ac = new POE_ACI_Statistic__c();
        ac.Opportunity__c = opp.Id;
        insert ac;
        Test.startTest();
        POE_SaveACIStatistics.initialSave(opp.Id, 34.000, 50.000);
        Test.stopTest();
        List<POE_ACI_Statistic__c> aci = [
            SELECT Id, Presentation__c
            FROM POE_ACI_Statistic__c
            WHERE Opportunity__c = :opp.Id
        ];
        System.assertEquals(1, aci.size(), 'ACI not inserted');
    }

    @isTest
    private static void testInitialSaveVlocityRetailInsert() {
        Boolean result;
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        inputMap.put('ContextId', opp.Id);
        inputMap.put('latitude', 33.50);
        inputMap.put('longitude', 50.2313);
        inputMap.put('origin', 'retail');
        Test.startTest();
        POE_SaveACIVlocity vl = new POE_SaveACIVlocity();
        result = vl.invokeMethod('Test', inputMap, outMap, options);
        Test.stopTest();
        List<POE_ACI_Statistic__c> aci = [
            SELECT Id, Order_Created__c
            FROM POE_ACI_Statistic__c
            WHERE Opportunity__c = :opp.Id
        ];
        System.assertEquals(1, aci.size(), 'ACI not inserted');
    }

    @isTest
    private static void testInitialSaveVlocityEventInsert() {
        Boolean result;
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        inputMap.put('ContextId', opp.Id);
        inputMap.put('latitude', 33.50);
        inputMap.put('longitude', 50.2313);
        inputMap.put('origin', 'event');
        Test.startTest();
        POE_SaveACIVlocity vl = new POE_SaveACIVlocity();
        result = vl.invokeMethod('Test', inputMap, outMap, options);
        Test.stopTest();
        List<POE_ACI_Statistic__c> aci = [
            SELECT Id, Order_Created__c
            FROM POE_ACI_Statistic__c
            WHERE Opportunity__c = :opp.Id
        ];
        System.assertEquals(1, aci.size(), 'ACI not inserted');
    }

    @isTest
    private static void testInitialSaveVlocityMapInsert() {
        Boolean result;
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        inputMap.put('ContextId', opp.Id);
        inputMap.put('latitude', 33.50);
        inputMap.put('longitude', 50.2313);
        inputMap.put('origin', 'maps');
        Test.startTest();
        POE_SaveACIVlocity vl = new POE_SaveACIVlocity();
        result = vl.invokeMethod('Test', inputMap, outMap, options);
        Test.stopTest();
        List<POE_ACI_Statistic__c> aci = [
            SELECT Id, Order_Created__c
            FROM POE_ACI_Statistic__c
            WHERE Opportunity__c = :opp.Id
        ];
        System.assertEquals(1, aci.size(), 'ACI not inserted');
    }

    @isTest
    private static void testInitialSaveVlocityPhoneSalesInsert() {
        Boolean result;
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        inputMap.put('ContextId', opp.Id);
        inputMap.put('latitude', 33.50);
        inputMap.put('longitude', 50.2313);
        inputMap.put('origin', 'phonesales');
        Test.startTest();
        POE_SaveACIVlocity vl = new POE_SaveACIVlocity();
        result = vl.invokeMethod('Test', inputMap, outMap, options);
        Test.stopTest();
        List<POE_ACI_Statistic__c> aci = [
            SELECT Id, Order_Created__c
            FROM POE_ACI_Statistic__c
            WHERE Opportunity__c = :opp.Id
        ];
        System.assertEquals(1, aci.size(), 'ACI not inserted');
    }

    @isTest
    private static void testInitialSaveVlocityRetailUpdate() {
        Boolean result;
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        POE_ACI_Statistic__c st = new POE_ACI_Statistic__c();
        st.Point_of_Disposition__latitude__s = 50;
        st.Point_of_Disposition__longitude__s = 30;
        st.Opportunity__c = opp.Id;
        insert st;
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        inputMap.put('ContextId', opp.Id);
        inputMap.put('latitude', 33.50);
        inputMap.put('longitude', 50.2313);
        inputMap.put('origin', 'retail');
        Test.startTest();
        POE_SaveACIVlocity vl = new POE_SaveACIVlocity();
        result = vl.invokeMethod('Test', inputMap, outMap, options);
        Test.stopTest();
        List<POE_ACI_Statistic__c> aci = [
            SELECT Id, Order_Created__c
            FROM POE_ACI_Statistic__c
            WHERE Opportunity__c = :opp.Id
        ];
        System.assertEquals(1, aci.size(), 'ACI not inserted');
    }

    @isTest
    private static void testInitialSaveVlocityEventUpdate() {
        Boolean result;
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        POE_ACI_Statistic__c st = new POE_ACI_Statistic__c();
        st.Point_of_Disposition__latitude__s = 50;
        st.Point_of_Disposition__longitude__s = 30;
        st.Opportunity__c = opp.Id;
        insert st;
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        inputMap.put('ContextId', opp.Id);
        inputMap.put('latitude', 33.50);
        inputMap.put('longitude', 50.2313);
        inputMap.put('origin', 'event');
        Test.startTest();
        POE_SaveACIVlocity vl = new POE_SaveACIVlocity();
        result = vl.invokeMethod('Test', inputMap, outMap, options);
        Test.stopTest();
        List<POE_ACI_Statistic__c> aci = [
            SELECT Id, Order_Created__c
            FROM POE_ACI_Statistic__c
            WHERE Opportunity__c = :opp.Id
        ];
        System.assertEquals(1, aci.size(), 'ACI not inserted');
    }

    @isTest
    private static void testInitialSaveVlocityMapUpdate() {
        Boolean result;
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        POE_ACI_Statistic__c st = new POE_ACI_Statistic__c();
        st.Point_of_Disposition__latitude__s = 50;
        st.Point_of_Disposition__longitude__s = 30;
        st.Opportunity__c = opp.Id;
        insert st;
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        inputMap.put('ContextId', opp.Id);
        inputMap.put('latitude', 33.50);
        inputMap.put('longitude', 50.2313);
        inputMap.put('origin', 'maps');
        Test.startTest();
        POE_SaveACIVlocity vl = new POE_SaveACIVlocity();
        result = vl.invokeMethod('Test', inputMap, outMap, options);
        Test.stopTest();
        List<POE_ACI_Statistic__c> aci = [
            SELECT Id, Order_Created__c
            FROM POE_ACI_Statistic__c
            WHERE Opportunity__c = :opp.Id
        ];
        System.assertEquals(1, aci.size(), 'ACI not inserted');
    }

    @isTest
    private static void testInitialSaveVlocityPhoneSalesUpdate() {
        Boolean result;
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        POE_ACI_Statistic__c st = new POE_ACI_Statistic__c();
        st.Point_of_Disposition__latitude__s = 50;
        st.Point_of_Disposition__longitude__s = 30;
        st.Opportunity__c = opp.Id;
        insert st;
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        inputMap.put('ContextId', opp.Id);
        inputMap.put('latitude', 33.50);
        inputMap.put('longitude', 50.2313);
        inputMap.put('origin', 'phonesales');
        Test.startTest();
        POE_SaveACIVlocity vl = new POE_SaveACIVlocity();
        result = vl.invokeMethod('Test', inputMap, outMap, options);
        Test.stopTest();
        List<POE_ACI_Statistic__c> aci = [
            SELECT Id, Order_Created__c
            FROM POE_ACI_Statistic__c
            WHERE Opportunity__c = :opp.Id
        ];
        System.assertEquals(1, aci.size(), 'ACI not inserted');
    }

    @isTest
    private static void testInitialSaveException() {
        Test.startTest();
        try {
            POE_SaveACIStatistics.initialSave('InvalidId', 34.000, 50.000);
            System.assert(false, 'Should have thrown an exception');
        } catch (Exception e) {
            System.assert(e.getMessage().contains('Script-thrown exception'), 'Exception message was wrong');
        }
        Test.stopTest();
    }
}