force-app/main/default/objects/Fraud_Validation_Statistics__c/Fraud_Validation_Statistics__c.object-meta.xml
<CustomObject>
    <label>Fraud Validation Statistics</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Fraud Validation Statistics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fraud Validation Statistics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fraud_Validation_Statistics__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fraud Validation Statistics</relationshipLabel>
    <relationshipName>Fraud_Validation_Statistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fraud_Validation_Statistics__c/fields/IP_Fraud_Flag__c.field-meta.xml
<CustomField>
    <fullName>IP_Fraud_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IP Fraud Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/POEIPStatisticValidator.cls
global without sharing class POEIPStatisticValidator implements vlocity_cmt.VlocityOpenInterface {
    
    global Boolean invokeMethod(
        String methodName,
        Map<String, Object> inputMap,
        Map<String, Object> outMap,
        Map<String, Object> options
    ) {
        Boolean result = true;

        try {
            if ('validateStatistic'.equalsIgnoreCase(methodName)) {
                validateStatistic(inputMap, outMap, options);
            } else {
                result = false;
            }
        } catch (Exception e) {
            result = false;
        }
        return result;
    }

    public void validateStatistic(
        Map<String, Object> inputMap,
        Map<String, Object> outMap,
        Map<String, Object> options
    ) {
        List<Fraud_Validation_Statistics__c> toUpdate = new List<Fraud_Validation_Statistics__c>();
        String contactId = (String) inputMap.get('ContactId');
        String state = (String) inputMap.get('State');
        Boolean toFlag = false;
        List<Fraud_Validation_Statistics__c> validations = new List<Fraud_Validation_Statistics__c>();
        Date d = System.today();
        Datetime dt = Datetime.newInstance(d, Time.newInstance(0, 0, 0, 0));
        String dayOfWeek = dt.format('EEEE');

        if (dayOfWeek == 'Monday') {
            validations = [
                SELECT Id, State__c, IP_Fraud_Flag__c
                FROM Fraud_Validation_Statistics__c
                WHERE CreatedDate >= LAST_N_DAYS:3 AND Contact__c = :contactId
            ];
        } else {
            validations = [
                SELECT Id, State__c, IP_Fraud_Flag__c
                FROM Fraud_Validation_Statistics__c
                WHERE CreatedDate >= LAST_N_DAYS:1 AND Contact__c = :contactId
            ];
        }
        for (Fraud_Validation_Statistics__c val : validations) {
            if (val.State__c != state) {
                toFlag = true;
            }
        }
        if (toFlag == true) {
            for (Fraud_Validation_Statistics__c val : validations) {
                val.IP_Fraud_Flag__c = true;
                toUpdate.add(val);
            }
            update toUpdate;
        }
    }
}