force-app/main/default/objects/Site_Survey_Question__c/Site_Survey_Question__c.object-meta.xml
<CustomObject>
    <label>Site Survey Question</label>
    <nameField>
        <displayFormat>SQ-{0000000}</displayFormat>
        <label>Site Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey_Question__c/fields/Dependent_Question__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dependent Question</label>
    <referenceTo>Site_Survey_Question__c</referenceTo>
    <relationshipLabel>Site Survey Questions</relationshipLabel>
    <relationshipName>Site_Survey_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/Exp_Parent_Ques_Response__c.field-meta.xml
<CustomField>
    <fullName>Exp_Parent_Ques_Response__c</fullName>
    <label>Expected Parent Question Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <description>Survey Section Header</description>
    <inlineHelpText>Section Header</inlineHelpText>
    <label>Section Header</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/is_active__c.field-meta.xml
<CustomField>
    <fullName>is_active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <inlineHelpText>Response Options</inlineHelpText>
    <label>Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <inlineHelpText>Survey Question</inlineHelpText>
    <label>Question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>dropdown</fullName>
            </value>
            <value>
                <fullName>radio</fullName>
            </value>
            <value>
                <fullName>textbox</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
            <value>
                <fullName>checkbox</fullName>
                <isActive>false</isActive>
                <label>checkbox</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Type__c</fullName>
    <label>Vendor Type</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the work type that the question is associated to. (PVFSL-879)</description>
    <label>Work Type</label>
    <referenceTo>WorkType</referenceTo>
    <relationshipLabel>Site Survey Questions</relationshipLabel>
    <relationshipName>Site_Survey_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Response__c/Site_Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Site Survey Response</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Survey Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey_Response__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>question__r.Order__c</formula>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Response__c/fields/question__c.field-meta.xml
<CustomField>
    <fullName>question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Site Survey Question</label>
    <referenceTo>Site_Survey_Question__c</referenceTo>
    <relationshipLabel>Site Survey Responses</relationshipLabel>
    <relationshipName>Site_Survey_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Response__c/fields/Question_Label__c.field-meta.xml
<CustomField>
    <fullName>Question_Label__c</fullName>
    <formula>question__r.Question__c</formula>
    <label>Question Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Response__c/fields/response__c.field-meta.xml
<CustomField>
    <fullName>response__c</fullName>
    <label>Answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Response__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Site Survey Responses</relationshipLabel>
    <relationshipName>Site_Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PV_SiteSurveyService.cls
public without sharing class PV_SiteSurveyService {
    
    @AuraEnabled(cacheable=true)
    public static List <SiteSurveyWrapper> fetchSurveyQuestions(String vendorType, String workTypeId) {
        List<SiteSurveyWrapper> srWrapper = new List<SiteSurveyWrapper>();
        List<Site_Survey_Question__c> questions = [
            SELECT
                Id,
                Name,
                Options__c,
                Dependent_Question__c,
                Exp_Parent_Ques_Response__c,
                Is_Dependent_Question__c,
                Order__c,
                Question__c,
                Header__c,
                is_active__c,
                Type__c
            FROM Site_Survey_Question__c
            WHERE (Work_Type__c = :workTypeId AND Work_Type__c != null)
                OR (Vendor_Type__c LIKE :'%' + vendorType + '%' AND Work_Type__c = null)
            ORDER BY Order__c ASC
        ];
        
        for (Site_Survey_Question__c ssq : questions) {
            SiteSurveyWrapper siteSurveyResponse = new SiteSurveyWrapper();
            siteSurveyResponse.question = ssq.Question__c;
            siteSurveyResponse.options =  ssq.Options__c;
            siteSurveyResponse.dependentQuestion = ssq.Dependent_Question__c;
            siteSurveyResponse.order = ssq.Order__c;
            siteSurveyResponse.header = ssq.Header__c;
            siteSurveyResponse.isActive = ssq.is_active__c;
            siteSurveyResponse.type = ssq.Type__c;
            siteSurveyResponse.isDependentQuestion = ssq.Is_Dependent_Question__c;
            siteSurveyResponse.expParentQuesResponse = ssq.Exp_Parent_Ques_Response__c;
            siteSurveyResponse.QuestionId = ssq.ID;
            siteSurveyResponse.value = '';
            
            srWrapper.add(siteSurveyResponse);
        }
        
        return srWrapper;
    }
    
    @AuraEnabled
    public static List<Site_Survey_Response__c> createSurveyResponses(List<Site_Survey_Response__c> surveyResponses) {
        try {
            System.debug('surveyResponses' + surveyResponses);
            upsert surveyResponses;
            return surveyResponses;
        } catch(Exception ex) {
            ExceptionUtil.publishException('SiteSurveyService.createSurveyResponses', ex.getLineNumber(), ex.getMessage(), ex.getStackTraceString());
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<SiteSurveyWrapper> getVendorType(String recordId) {
        ServiceAppointment serviceAppointment = [
            SELECT
                Id,
                FSSK__FSK_Work_Order__r.Vendor__c,
                FSSK__FSK_Work_Order__r.WorkTypeId,
                FSSK__FSK_Work_Order__r.WorkType.Name,
                FSSK__FSK_Work_Order__r.WorkType.Site_Survey_Allowed_For_Closeout__c,
                Status
            FROM ServiceAppointment WHERE Id = :recordId
            LIMIT 1
        ];

        List<Site_Survey_Question__c> questions = [
            SELECT Id
            FROM Site_Survey_Question__c
            WHERE (Work_Type__c = :serviceAppointment.FSSK__FSK_Work_Order__r.WorkTypeId AND Work_Type__c != null)
                OR (Vendor_Type__c LIKE :'%' + serviceAppointment.FSSK__FSK_Work_Order__r.Vendor__c + '%' AND Work_Type__c = null)
            ORDER BY Order__c ASC
        ];
        
        Boolean isCompVisible = !questions.isEmpty();
        
        List<SiteSurveyWrapper> siteSurveyList = new List<SiteSurveyWrapper>();
        
        SiteSurveyWrapper wrapper = new SiteSurveyWrapper();
        if (isCompVisible) {
            wrapper.availableForComponent = true;
            wrapper.status = serviceAppointment.Status;
            wrapper.vendorType = serviceAppointment.FSSK__FSK_Work_Order__r.Vendor__c;
            wrapper.workTypeId = serviceAppointment.FSSK__FSK_Work_Order__r.WorkTypeId;
            wrapper.siteSurveyAllowedForCloseout = serviceAppointment.FSSK__FSK_Work_Order__r.WorkType.Site_Survey_Allowed_For_Closeout__c;
            siteSurveyList.add(wrapper);
            return siteSurveyList;
        } else {
            wrapper.availableForComponent = false;
            wrapper.status = serviceAppointment.Status;
            siteSurveyList.add(wrapper);
            return siteSurveyList;
        }
    }
    
    @AuraEnabled
    public static List <SiteSurveyWrapper> getSurveyResponse(String recordId, String vendorType, String workTypeId) {
        List <SiteSurveyWrapper> srWrapper = new List<SiteSurveyWrapper>();
        Map<Id, Site_Survey_Response__c> responseMap = new Map<Id, Site_Survey_Response__c>();
        List<Site_Survey_Response__c> response = [
            SELECT
                Id,
                Service_Appointment__c,
                response__c,
                question__c
            FROM Site_Survey_Response__c
            WHERE Service_Appointment__c = :recordId
        ];
        
        List<Site_Survey_Question__c> questions = [
            SELECT
                Id,
                Name,
                Options__c,
                Dependent_Question__c,
                Exp_Parent_Ques_Response__c,
                Is_Dependent_Question__c,
                Order__c,
                Question__c,
                Header__c,
                is_active__c,
                Type__c
            FROM Site_Survey_Question__c
            WHERE (Work_Type__c = :workTypeId AND Work_Type__c != null)
                OR (Vendor_Type__c LIKE :'%' + vendorType + '%' AND Work_Type__c = null)
            ORDER BY Order__c ASC
        ];
        
        for (Site_Survey_Response__c surveyResponses : response) {
            responseMap.put(surveyResponses.question__c,surveyResponses);
        }
        for (Site_Survey_Question__c surveyQuestion : questions) {
            SiteSurveyWrapper siteSurveyResponse = new SiteSurveyWrapper();
            if (responseMap.containsKey(surveyQuestion.Id)) {
                Site_Survey_Response__c responseRecord = responseMap.get(surveyQuestion.Id);
                if (responseRecord != null && responseRecord.question__c == surveyQuestion.Id) {
                    siteSurveyResponse.responseId = responseRecord.Id;
                    siteSurveyResponse.value = responseRecord.response__c;
                }
            }
            siteSurveyResponse.question = surveyQuestion.Question__c;
            siteSurveyResponse.options =  surveyQuestion.Options__c;
            siteSurveyResponse.dependentQuestion = surveyQuestion.Dependent_Question__c;
            siteSurveyResponse.order = surveyQuestion.Order__c;
            siteSurveyResponse.header = surveyQuestion.Header__c;
            siteSurveyResponse.isActive = surveyQuestion.is_active__c;
            siteSurveyResponse.type = surveyQuestion.Type__c;
            siteSurveyResponse.isDependentQuestion = surveyQuestion.Is_Dependent_Question__c;
            siteSurveyResponse.expParentQuesResponse = surveyQuestion.Exp_Parent_Ques_Response__c;
            siteSurveyResponse.QuestionId = surveyQuestion.Id;
            srWrapper.add(siteSurveyResponse);
        }
        return srWrapper;
    }
    
    @AuraEnabled
    public static List<Site_Survey_Response__c> getResponse(String saId) {
        return [
            SELECT response__c, Question_Label__c
            FROM Site_Survey_Response__c
            WHERE Service_Appointment__c = :saId
        ];
    }
    
    public class SiteSurveyWrapper {
        @AuraEnabled
        public boolean availableForComponent;
        @AuraEnabled
        public String status;
        @AuraEnabled
        public String vendorType;
        @AuraEnabled
        public String workTypeId;
        @AuraEnabled
        public String name {get; set;}
        @AuraEnabled
        public String options {get; set;}
        @AuraEnabled
        public String dependentQuestion {get; set;}
        @AuraEnabled
        public String expParentQuesResponse {get; set;}
        @AuraEnabled
        public Boolean isDependentQuestion {get; set;}
        @AuraEnabled
        public Decimal order {get; set;}
        @AuraEnabled
        public String question {get; set;}
        @AuraEnabled
        public String header {get; set;}
        @AuraEnabled
        public Boolean isActive {get; set;}
        @AuraEnabled
        public String type {get; set;}
        @AuraEnabled
        public String value {get; set;}
        @AuraEnabled
        public String QuestionId {get; set;}
        @AuraEnabled
        public String responseId {get; set;}
        @AuraEnabled
        public Boolean siteSurveyAllowedForCloseout {get; set;}
        
    }
    
}