force-app/main/default/objects/Site_Survey_Question__c/Site_Survey_Question__c.object-meta.xml
<CustomObject>
    <label>Site Survey Question</label>
    <nameField>
        <displayFormat>SQ-{0000000}</displayFormat>
        <label>Site Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey_Question__c/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <description>Survey Section Header</description>
    <inlineHelpText>Section Header</inlineHelpText>
    <label>Section Header</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/is_active__c.field-meta.xml
<CustomField>
    <fullName>is_active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <inlineHelpText>Response Options</inlineHelpText>
    <label>Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <inlineHelpText>Survey Question</inlineHelpText>
    <label>Question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>dropdown</fullName>
            </value>
            <value>
                <fullName>radio</fullName>
            </value>
            <value>
                <fullName>textbox</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
            <value>
                <fullName>checkbox</fullName>
                <isActive>false</isActive>
                <label>checkbox</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Type__c</fullName>
    <label>Vendor Type</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Question__c/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the work type that the question is associated to. (PVFSL-879)</description>
    <label>Work Type</label>
    <referenceTo>WorkType</referenceTo>
    <relationshipLabel>Site Survey Questions</relationshipLabel>
    <relationshipName>Site_Survey_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Response__c/Site_Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Site Survey Response</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Survey Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey_Response__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>question__r.Order__c</formula>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Response__c/fields/question__c.field-meta.xml
<CustomField>
    <fullName>question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Site Survey Question</label>
    <referenceTo>Site_Survey_Question__c</referenceTo>
    <relationshipLabel>Site Survey Responses</relationshipLabel>
    <relationshipName>Site_Survey_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Response__c/fields/response__c.field-meta.xml
<CustomField>
    <fullName>response__c</fullName>
    <label>Answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey_Response__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Site Survey Responses</relationshipLabel>
    <relationshipName>Site_Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PV_SiteSurveyServiceTest.cls
@isTest
public class PV_SiteSurveyServiceTest {
    @testSetup
    static void testData() {
        System.runAs(new User(Id = UserInfo.getUserId())) {
            Account acc = PV_TestDataFactory.createAccount('Test Account', true);
            contact con = PV_TestDataFactory.createContact('Test', 'contact_01', true, acc);
            OperatingHours opHrs = PV_TestDataFactory.createOperatingHours('East - Mon-Fri 8am - 5pm', true);
            ServiceTerritory pst = PV_TestDataFactory.createParentServiceTerritory(true, 'ST-01', opHrs);
            ServiceTerritory childServiceTerritory = PV_TestDataFactory.createServiceTerritoryForAccount(true, acc, pst);
            User usr = PV_TestDataFactory.createTechnicianUser(true, con);
            PV_TestDataFactory.assignPermissionSetGroupToUser(true, usr, 'FSL_Technician');
            ServiceResource serviceRes = PV_TestDataFactory.createServiceResource(true, acc, con, usr);
            ServiceTerritoryMember stm = PV_TestDataFactory.createServiceTerritoryMember(true, serviceRes, childServiceTerritory, 'P');
            WorkType wt = PV_TestDataFactory.createWorkType('ImpSkill', false);
            wt.Site_Survey_Allowed_For_Closeout__c = true;
            insert wt;
            WorkOrder wo = PV_TestDataFactory.createWorkOrder(usr, wt, true);
            
            ServiceAppointment sa = new ServiceAppointment();
            sa.ParentRecordId = wo.Id;
            sa.FSSK__FSK_Work_Order__c = wo.Id;
            sa.ServiceTerritoryId = pst.Id;
            sa.WorkTypeId = wt.Id;
            insert sa;
            
            Site_Survey_Question__c siteQuestion = new Site_Survey_Question__c();
            siteQuestion.Type__c = 'Dropdown';
            siteQuestion.is_active__c = true;
            siteQuestion.Header__c = 'Question 1';
            siteQuestion.Question__c = 'Mount Conditions';
            siteQuestion.Options__c = 'New,Existing';
            siteQuestion.Order__c = 1;
            siteQuestion.Vendor_Type__c = 'T-Mobile';
            insert siteQuestion;
        }
    }
    
    @isTest
    static void testMethod1() {
        List<Site_Survey_Question__c> siteQuestion = [SELECT Id, Name, Type__c, Vendor_Type__c, Work_Type__c FROM Site_Survey_Question__c];
        List<ServiceAppointment> sa = [SELECT Id FROM ServiceAppointment];
        List<Site_Survey_Response__c> ssr = new List<Site_Survey_Response__c>();
        Site_Survey_Response__c ssResponse = new Site_Survey_Response__c();
        ssResponse.question__c = siteQuestion[0].Id;
        ssResponse.response__c = 'test Response';
        ssResponse.Service_Appointment__c = sa[0].Id;
        ssr.add(ssResponse);
        Test.startTest();
        PV_SiteSurveyService.fetchSurveyQuestions(siteQuestion[0].Vendor_Type__c, null);
        PV_SiteSurveyService.createSurveyResponses(ssr);
        PV_SiteSurveyService.getVendorType(sa[0].Id);
        PV_SiteSurveyService.getResponse(sa[0].Id);
        PV_SiteSurveyService.getSurveyResponse(sa[0].Id, siteQuestion[0].Vendor_Type__c, null);
        Test.stopTest(); 
    }
    
    @isTest
    static void testException(){
        List<Site_Survey_Question__c> siteQuestion = [SELECT Id, Name, Type__c FROM Site_Survey_Question__c];
        List<Site_Survey_Response__c> ssr = new List<Site_Survey_Response__c>();
        Site_Survey_Response__c ssResponse = new Site_Survey_Response__c();
        ssResponse.response__c = 'ssr';
        ssr.add(ssResponse);
        Test.startTest();
            try {
                PV_SiteSurveyService.createSurveyResponses(ssr);
            } catch(exception ex) {
                Assert.areEqual('Script-thrown exception', ex.getMessage());
            }
        Test.stopTest();
    }
}