force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <label>Exception</label>
    <nameField>
        <displayFormat>EX-{00000000}</displayFormat>
        <label>Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception__c/fields/Antenna_credit__c.field-meta.xml
<CustomField>
    <fullName>Antenna_credit__c</fullName>
    <label>Antenna credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Coverage</fullName>
            </value>
            <value>
                <fullName>Commercial Add-on</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exception__c/fields/ODU_move__c.field-meta.xml
<CustomField>
    <fullName>ODU_move__c</fullName>
    <label>ODU move</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Reinstall_Commercial__c.field-meta.xml
<CustomField>
    <fullName>Reinstall_Commercial__c</fullName>
    <label>Reinstall Commercial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Reinstall_Service_Call__c.field-meta.xml
<CustomField>
    <fullName>Reinstall_Service_Call__c</fullName>
    <label>Reinstall (Service Call)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Reinstall_Upgrade__c.field-meta.xml
<CustomField>
    <fullName>Reinstall_Upgrade__c</fullName>
    <label>Reinstall (Upgrade)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Repair__c.field-meta.xml
<CustomField>
    <fullName>Repair__c</fullName>
    <label>Repair</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Repair_Commercial__c.field-meta.xml
<CustomField>
    <fullName>Repair_Commercial__c</fullName>
    <label>Repair Commercial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipName>Exceptionns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipName>Exceptionns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>ODU_move__c  +  Antenna_credit__c + Reinstall_Service_Call__c + Reinstall_Upgrade__c + Reinstall_Commercial__c +  Repair__c +   Repair_Commercial__c  +  Trip_Fee__c +  Product_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Trip_Fee__c.field-meta.xml
<CustomField>
    <fullName>Trip_Fee__c</fullName>
    <label>Trip Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trip fees</fullName>
            </value>
            <value>
                <fullName>Repair Commercial</fullName>
            </value>
            <value>
                <fullName>Antenna credit</fullName>
            </value>
            <value>
                <fullName>ODU move</fullName>
            </value>
            <value>
                <fullName>Reinstall (Upgrade)</fullName>
            </value>
            <value>
                <fullName>Reinstall (Service Call)</fullName>
            </value>
            <value>
                <fullName>Reinstall Commercial</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Equipment credit</fullName>
            </value>
            <value>
                <fullName>Equipment Replacement</fullName>
                <isActive>false</isActive>
                <label>Equipment Replacement</label>
            </value>
            <value>
                <fullName>In warranty service calls</fullName>
                <isActive>false</isActive>
                <label>In warranty service calls</label>
            </value>
            <value>
                <fullName>Quality of work</fullName>
                <isActive>false</isActive>
                <label>Quality of work</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PV_ExceptionTriggerHandler.cls
/**
* @description       : Handler Class PV_ExceptionTrigger
* @author            : Impaqtive DevTeam
* @group             :
* @last modified on  : 12-06-2023
* @last modified by  : Impaqtive DevTeam
* Modifications Log
* Ver   Date         Author            Modification
* 1.0                      Initial Version
**/
public class PV_ExceptionTriggerHandler{
    public static void exceptionAfterInsert (List<Exception__c> exceptionList){
        
        String categoryTypeList = '';
        Set<String> typeValues = new Set<String>();
        Set<Id> serviceAppId = new Set<Id>();
        List<Id> serviceResId = new List<Id>();
        List<Id> accountId = new List<Id>();
        List<Id> contactId = new List<Id>();
        Set<String> categoryType = new Set<String>();
        Map<String,Decimal> typeAmountMap = new Map<String,Decimal> ();
        Map<String,String> typeCategoryMap = new Map<String,String>();
        for(Exception__c exp : exceptionList ){
            serviceAppId.add(exp.Service_Appointment__c);
            List<String> selections = exp.Type__c.split(';');
            if (selections != null && !selections.isEmpty()) {
                typeValues.addAll(selections);
            }
        }
        
        List<ServiceAppointment> serviceAppList = [SELECT FSSK__FSK_Assigned_Service_Resource__c FROM ServiceAppointment WHERE Id IN:serviceAppId ];
        for(ServiceAppointment serviceResourceId : serviceAppList ){
            serviceResId.add(serviceResourceId.FSSK__FSK_Assigned_Service_Resource__c);  
        }
        System.debug('serviceAppId>>>>>'+serviceAppId);
        system.debug('typeValues>>>>>>>'+typeValues);
        try{
            for(String totalAmount : typeValues ){
                typeAmountMap.put(totalAmount,PV_Constant.typeAmount.get(totalAmount));
                
            }
            for(String typeCategory : typeValues ){
                typeCategoryMap.put(typeCategory,PV_Constant.typeCategory.get(typeCategory));
            }
            
            for(String categoryList : typeValues){
                categoryType.add(typeCategoryMap.get(categoryList));            
            }
            System.debug('categoryType>>>>.'+categoryType);
            
            
            for(Exception__c categoryExcep : exceptionList ){
                for(String categoryTypevalues :categoryType){
                    categoryTypeList += categoryTypevalues +';';
                    categoryExcep.Category__c = categoryTypeList;
                    System.debug('categoryTypeList>>>>>>>>>>>'+categoryTypeList);
                }
            } 
            System.debug('categoryTypeList>>>>>>>>>>>'+categoryTypeList);
            
            for(Exception__c exp : exceptionList ){
                for(String typeCategory : typeValues ){
                    //exp.Total_Amount__c = totalAmount;
                    exp.Antenna_credit__c = typeAmountMap.get('Antenna credit')!=null?typeAmountMap.get('Antenna credit'):null;
                    exp.Reinstall_Service_Call__c = typeAmountMap.get('Reinstall (Service Call)')!=null?typeAmountMap.get('Reinstall (Service Call)'):null;
                    exp.Reinstall_Upgrade__c = typeAmountMap.get('Reinstall (Upgrade)')!=null?typeAmountMap.get('Reinstall (Upgrade)'):null;
                    exp.Reinstall_Commercial__c = typeAmountMap.get('Reinstall Commercial')!=null?typeAmountMap.get('Reinstall Commercial'):null;
                    exp.Repair__c = typeAmountMap.get('Repair')!=null?typeAmountMap.get('Repair'):null;
                    exp.ODU_move__c = typeAmountMap.get('ODU move')!=null?typeAmountMap.get('ODU move'):null;
                    exp.Repair_Commercial__c = typeAmountMap.get('Repair Commercial')!=null?typeAmountMap.get('Repair Commercial'):null;
                    //exp.Trip_Fee__c = typeAmountMap.get('Trip Fees')!=null?typeAmountMap.get('Trip Fees'):null;
                    exp.Service_Resource__c = serviceResId[0]!=null?serviceResId[0]:null;
                }
            }
            
            //System.debug('totalAmount>>>>>>>>>'+totalAmount);
            System.debug('totalAmountMap>>>>>>'+typeAmountMap);
            System.debug('typeCategoryMap>>>>>'+typeCategoryMap);
        }
        catch(Exception ex) {
            ExceptionUtil.publishException('PV_ExceptionTriggerHandler.exceptionAfterInsert', ex.getLineNumber(), ex.getMessage(), ex.getStackTraceString());
        }
    }
}