force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <label>Exception</label>
    <nameField>
        <displayFormat>EX-{00000000}</displayFormat>
        <label>Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Product__c/Exception_Product__c.object-meta.xml
<CustomObject>
    <label>Exception Product</label>
    <nameField>
        <displayFormat>EP-{0000}</displayFormat>
        <label>Exception Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Product__c/fields/Exception__c.field-meta.xml
<CustomField>
    <fullName>Exception__c</fullName>
    <label>Exception</label>
    <referenceTo>Exception__c</referenceTo>
    <relationshipName>Exception_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PV_ExceptionProductTriggerHandler.cls
/**
* @description       : Handler Class for PV_ServiceTerritoryTrigger
* @author            : Impaqtive DevTeam
* @group             :
* @last modified on  : 
* @last modified by  : Impaqtive DevTeam
* Modifications Log
* Ver                 :  1.0  
* Date               : 03-08-2023
**/
public class PV_ExceptionProductTriggerHandler {
    
    //unlocks exception record approval to insert products into exception related list 
    public static void handleBeforeInsert(List<Exception_Product__c> exceptionProductList){
        try{
            for(Exception_Product__c exceptionProduct:exceptionProductList){
                if(Approval.isLocked(exceptionProduct.Exception__c)){
                    Approval.unlock(exceptionProduct.Exception__c);
                }
            }
        }
        catch (Exception ex) {
            ExceptionUtil.publishException('PV_ExceptionProductTriggerHandler.handleBeforeInsert', ex.getLineNumber(), ex.getMessage(), ex.getStackTraceString());
            
        }
    }
    
    //locks exception record after product insert 
    public static void handleAfterInsert(List<Exception_Product__c> exceptionProductList){
       
            for(Exception_Product__c exceptionProduct:exceptionProductList){
                Approval.lock(exceptionProduct.Exception__c);
            }
        

    }
}