force-app/main/default/objects/Message_Log__c/Message_Log__c.object-meta.xml
<CustomObject>
    <description>This object will store the SMS logs for the Twilio integration. (PVFSL-379)</description>
    <label>Message Log</label>
    <nameField>
        <displayFormat>SMS-{0000000}</displayFormat>
        <label>Message Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Message Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message_Log__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Message Logs</relationshipLabel>
    <relationshipName>Message_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Message_Log__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <description>This field stores the SMS directionality. (PVFSL-379)</description>
    <label>Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Message_Log__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Message Logs</relationshipLabel>
    <relationshipName>Message_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message_Log__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/FSL_CommTimelineMessageLog.cls
public with sharing class FSL_CommTimelineMessageLog implements FSL_CommunicationTimelineItem.GetRecords {

    public static List<FSL_CommunicationTimelineItem> getRecords(Id recordId, List<Id> excludeIds, Integer queryLimit) {
        List<FSL_CommunicationTimelineItem> items = new List<FSL_CommunicationTimelineItem>();
        for (Message_Log__c messageLog : [
            SELECT
                Id,
                Sent_Date__c,
                CreatedBy.Name,
                Contact__r.Name,
                To__c,
                Body__c,
                Direction__c
            FROM Message_Log__c
            WHERE Service_Appointment__c = :recordId
                AND Id NOT IN :excludeIds
            ORDER BY Sent_Date__c DESC
            LIMIT :queryLimit
        ]) {
            items.add(new FSL_CommunicationTimelineItem(
                messageLog.Id,
                'SMS',
                messageLog.Sent_Date__c,
                messageLog.Direction__c == 'Inbound' ? messageLog.Contact__r.Name : messageLog.CreatedBy.Name,
                messageLog.To__c,
                '',
                messageLog.Body__c,
                messageLog.Direction__c == 'Inbound'
            ));
        }
        return items;
    }
}