force-app/main/default/objects/Audit__c/fields/All_Required_Photos__c.field-meta.xml
<CustomField>
    <fullName>All_Required_Photos__c</fullName>
    <label>All Required Photos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Antenna_Assembly__c.field-meta.xml
<CustomField>
    <fullName>Antenna_Assembly__c</fullName>
    <inlineHelpText>Did the Technician assemble the antenna properly?</inlineHelpText>
    <label>Antenna Assembly</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Antenna_Mount__c.field-meta.xml
<CustomField>
    <fullName>Antenna_Mount__c</fullName>
    <inlineHelpText>Did the Technician mount the antenna properly?</inlineHelpText>
    <label>Antenna Mount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Antenna_Pointing__c.field-meta.xml
<CustomField>
    <fullName>Antenna_Pointing__c</fullName>
    <label>Antenna Pointing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Approved_Cabling_Aesthetics__c.field-meta.xml
<CustomField>
    <fullName>Approved_Cabling_Aesthetics__c</fullName>
    <label>Approved Cabling &amp; Aesthetics</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Approved_Mount__c.field-meta.xml
<CustomField>
    <fullName>Approved_Mount__c</fullName>
    <label>Approved Mount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Audit_Result__c.field-meta.xml
<CustomField>
    <fullName>Audit_Result__c</fullName>
    <label>Audit Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PASS</fullName>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Cable_Routing__c.field-meta.xml
<CustomField>
    <fullName>Cable_Routing__c</fullName>
    <inlineHelpText>Did the Technician route the cable properly?</inlineHelpText>
    <label>Cable Routing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Equipment_Cable_ODU__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Cable_ODU__c</fullName>
    <label>Equipment (Cable &amp; ODU)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Hex_Pole__c.field-meta.xml
<CustomField>
    <fullName>Hex_Pole__c</fullName>
    <label>Hex Pole</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Line_of_Sight_10__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Sight_10__c</fullName>
    <label>Line of Sight (+/- 10*)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Non_Pen__c.field-meta.xml
<CustomField>
    <fullName>Non_Pen__c</fullName>
    <label>Non-Pen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/ODU_Mount_Hardware__c.field-meta.xml
<CustomField>
    <fullName>ODU_Mount_Hardware__c</fullName>
    <label>ODU Mount &amp; Hardware</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/On_Site__c.field-meta.xml
<CustomField>
    <fullName>On_Site__c</fullName>
    <label>On-Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Point_Peak__c.field-meta.xml
<CustomField>
    <fullName>Point_Peak__c</fullName>
    <inlineHelpText>Did the Technician Point &amp; Peak the system properly?</inlineHelpText>
    <label>Point &amp; Peak</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Post_Install_Customer_Experience__c.field-meta.xml
<CustomField>
    <fullName>Post_Install_Customer_Experience__c</fullName>
    <inlineHelpText>Did the technician perform the Post-Install Customer Experience procedures properly?</inlineHelpText>
    <label>Post-Install Customer Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Pre_Install_Customer_Experience__c.field-meta.xml
<CustomField>
    <fullName>Pre_Install_Customer_Experience__c</fullName>
    <inlineHelpText>Did the Technician follow the Pre-Install Customer Experience procedures properly?</inlineHelpText>
    <label>Pre-Install Customer Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Quality_Follow_Up_Needed__c.field-meta.xml
<CustomField>
    <fullName>Quality_Follow_Up_Needed__c</fullName>
    <label>Quality Follow-Up Needed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Roof__c.field-meta.xml
<CustomField>
    <fullName>Roof__c</fullName>
    <label>Roof</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Round_Pole__c.field-meta.xml
<CustomField>
    <fullName>Round_Pole__c</fullName>
    <label>Round Pole</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/S_Mount__c.field-meta.xml
<CustomField>
    <fullName>S_Mount__c</fullName>
    <label>S-Mount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <inlineHelpText>Did the Technician perform a proper Site Survey?</inlineHelpText>
    <label>Site Survey</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Stubby__c.field-meta.xml
<CustomField>
    <fullName>Stubby__c</fullName>
    <label>Stubby</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/System_Grounded__c.field-meta.xml
<CustomField>
    <fullName>System_Grounded__c</fullName>
    <inlineHelpText>Did the Technician ground the system properly?</inlineHelpText>
    <label>System Grounded</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/System_Grounded_to_NEC_Ground_Source__c.field-meta.xml
<CustomField>
    <fullName>System_Grounded_to_NEC_Ground_Source__c</fullName>
    <label>System Grounded to NEC Ground Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/System_Provisioned__c.field-meta.xml
<CustomField>
    <fullName>System_Provisioned__c</fullName>
    <inlineHelpText>Did the Technician Provision the system properly?</inlineHelpText>
    <label>System Provisioned</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Undereave__c.field-meta.xml
<CustomField>
    <fullName>Undereave__c</fullName>
    <label>Undereave</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Virtual__c.field-meta.xml
<CustomField>
    <fullName>Virtual__c</fullName>
    <label>Virtual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Wall__c.field-meta.xml
<CustomField>
    <fullName>Wall__c</fullName>
    <label>Wall</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Audit_Results</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Audits</relationshipLabel>
    <relationshipName>Audits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PV_FSL_Config__mdt/PV_FSL_Config__mdt.object-meta.xml
<CustomObject>
    <label>PV FSL Configuration</label>
    <pluralLabel>PV FSL Configurations</pluralLabel>
</CustomObject>

force-app/main/default/classes/PV_AuditController.cls
/**
* @description       :Controller  Class for audit screen
* @author            : Impaqtive DevTeam
* @last modified on  : 07-24-2023
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
* Modifications Log
* Ver   Date         Author            	   Modification
* 1.0   03/07/2023   Impaqtive DevTeam     Initial Version
**/
public without sharing class PV_AuditController {
    
    //Method for completed audit record
    @AuraEnabled(cacheable=true)
    public static boolean getCompletedAudit(String workOrderId) {
        
        system.debug('workOrderId'+workOrderId);
        try{        
            String userProfile=[SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1].Name;
            List<string> readProfiles = PV_FSL_Config__mdt.getInstance('Audit_Read_access').Value__c.split(',');
            boolean py = true;
            system.debug(readProfiles);
            List<Audit__c> auditList=[select id,
                                      Audit_Result__c from Audit__c 
                                      where Work_Order__c=:workOrderId AND Audit_Result__c != NULL 
                                      order by CreatedDate desc limit 1];
            
            List<ServiceAppointment> appointmentList=[select id,
                                      Status from ServiceAppointment 
                                      where Status='Complete' AND ParentRecordId =:workOrderId
                                      order by CreatedDate desc limit 1];


            if(appointmentList.isEmpty()){
                return false;
            }
            
            if((readProfiles.contains(userProfile)) &&(auditList.isEmpty())){

                     py= false;              
            }
            return py; 
            
        }catch (Exception ex) {
            ExceptionUtil.publishException('PV_AuditController.getCompletedAudit', ex.getLineNumber(), ex.getMessage(), ex.getStackTraceString());
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    //Method for related audit record
    @AuraEnabled(cacheable=true)
    public static Payload getAudit(String workOrderId) {
        
        try{        
            String userProfile=[SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1].Name;
            List<string> EditRequiredProfiles = PV_FSL_Config__mdt.getInstance('Audit_Edit_access').Value__c.split(',');
            Payload py;
            List<Audit__c> auditList=[select id,
                                      On_Site__c,
                                      Virtual__c,
                                      Roof__c,
                                      Stubby__c,
                                      Round_Pole__c,
                                      S_Mount__c,
                                      Non_Pen__c,
                                      Hex_Pole__c,
                                      Undereave__c,
                                      Approved_Mount__c,
                                      Wall__c,
                                      All_Required_Photos__c,
                                      Quality_Follow_Up_Needed__c,
                                      Antenna_Pointing__c,
                                      Equipment_Cable_ODU__c,
                                      Line_of_Sight_10__c,
                                      ODU_Mount_Hardware__c,
                                      Approved_Cabling_Aesthetics__c,
                                      System_Grounded_to_NEC_Ground_Source__c,
                                      Pre_Install_Customer_Experience__c,
                                      Site_Survey__c,
                                      Antenna_Assembly__c,
                                      Antenna_Mount__c,
                                      Cable_Routing__c,
                                      System_Grounded__c,
                                      Point_Peak__c,
                                      System_Provisioned__c,
                                      Post_Install_Customer_Experience__c,
                                      Audit_Result__c from Audit__c where Work_Order__c=:workOrderId order by CreatedDate desc limit 1];
            
            
            
            if(EditRequiredProfiles.contains(userProfile)){
                
                py=new Payload(auditList,true);
                
            }else{
                py=new Payload(auditList,false);
            }
            return py; 
            
        }catch (Exception ex) {
            ExceptionUtil.publishException('PV_AuditController', ex.getLineNumber(), ex.getMessage(), ex.getStackTraceString());
            throw new AuraHandledException(ex.getMessage());
        }
    }
    //Method to update audit record
    @AuraEnabled
    public static void updateAudit(Audit__c auditrecord) {
        try{
            update auditrecord;
            
        }catch (Exception ex) {
            ExceptionUtil.publishException('PV_AuditController', ex.getLineNumber(), ex.getMessage(), ex.getStackTraceString());
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    //Method to return audit options
    @AuraEnabled
    public static List<PicklistOptions> auditOptions() {
        
        List<PicklistOptions> auditOptions=new List<PicklistOptions>();
        List<string> auditOptionList = PV_FSL_Config__mdt.getInstance('Audit_options').Value__c.split(',');
        for(String Soption:auditOptionList){
            PicklistOptions option=new PicklistOptions();
            option.value=option.label=Soption;
            auditOptions.add(option);
        }
        
        return auditOptions;
        
    }
    //Method to return quality Options
    @AuraEnabled
    public static List<PicklistOptions> qualityOptions() {
        
        List<PicklistOptions> auditOptions=new List<PicklistOptions>();
        List<string> auditOptionList = PV_FSL_Config__mdt.getInstance('Audit_qualityFollwup_options').Value__c.split(',');
        for(String Soption:auditOptionList){
            PicklistOptions option=new PicklistOptions();
            option.value=option.label=Soption;
            auditOptions.add(option);
        }
        
        return auditOptions;
        
    }
    //Method to return audit Result
    @AuraEnabled
    public static List<PicklistOptions> auditResult() {
        
        List<PicklistOptions> auditOptions=new List<PicklistOptions>();
        List<string> auditOptionList = PV_FSL_Config__mdt.getInstance('Audit_results').Value__c.split(',');
        for(String Soption:auditOptionList){
            PicklistOptions option=new PicklistOptions();
            option.value=option.label=Soption;
            auditOptions.add(option);
        }
        
        return auditOptions;
        
    }
    
    public class Payload{
        
        @AuraEnabled public List<Audit__c> auditList;
        @AuraEnabled public Boolean IsEditAccess;
        
        public  Payload(List<Audit__c> auditList,Boolean Isedit){
            
            this.auditList=auditList;
            this.IsEditAccess=Isedit;
        }
        
    }
    
    public class PicklistOptions{
        
        @AuraEnabled public String value;
        @AuraEnabled public String label;
        
    }
    
}