force-app/main/default/objects/MDU_Chuzo__c/MDU_Chuzo__c.object-meta.xml
<CustomObject>
    <label>MDU Chuzo</label>
    <nameField>
        <label>MDU Chuzo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDUs Chuzo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MDU_Chuzo__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MDU_Chuzo__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <label>Zip Code</label>
    <nameField>
        <displayFormat>Zip-{00000}</displayFormat>
        <label>Zip Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/POE_GeoCodeMDUs.cls
public class POE_GeoCodeMDUs {
    @InvocableMethod(label='Geocode MDUs' description='Geocode MDUs with address updates or during creation.')
    public static void updateMDUs(List<MDU_Chuzo__c> events) {
        String address =
            events[0].Street_Address__c +
            ', ' +
            events[0].City__c +
            ', ' +
            events[0].State__c +
            ' ' +
            events[0].Zip_Code__c +
            ' USA';
        geoCodeRecord(address, events[0].Id);
    }

    @future(callout=true)
    public static void geoCodeRecord(String address, String recordId) {
        Map<string, object> options = new Map<String, Object>{ 'version' => '1', 'address' => address };
        Map<String, Object> response = new Map<String, Object>();
        if (!Test.isRunningTest()) {
            response = maps.API.Geocode(options);
        } else {
            Map<String, Object> position = new Map<String, Object>();
            position.put('lat', 37.7897784);
            position.put('lng', -122.3973206);
            Map<String, Object> data = new Map<String, Object>();
            data.put('position', position);
            response.put('data', data);
        }
        try {
            Map<String, Object> data = (Map<String, Object>) response.get('data');
            Map<String, Object> position = (Map<String, Object>) data.get('position');
            Decimal lat = (Decimal) position.get('lat');
            Decimal lng = (Decimal) position.get('lng');
            MDU_Chuzo__c mdu = [
                SELECT Id, Location__Latitude__s, Location__Longitude__s
                FROM MDU_Chuzo__c
                WHERE Id = :recordId
            ];
            mdu.Location__Latitude__s = lat;
            mdu.Location__Longitude__s = lng;
            update mdu;
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }

    public class Output {
        public String baseUrl;
        public Data data;
        public String source;
        public String success;
    }

    public class Data {
        public String houseNumber;
        public String matchLevel;
        public Integer score;
        public String country;
        public String postal;
        public String state;
        public String city;
        public String street;
        public String fullAddress;
        public Position position;
    }

    public class Position {
        public Decimal lng;
        public Decimal lat;
    }
    
}