force-app/main/default/objects/Error_Alert__e/Error_Alert__e.object-meta.xml
<CustomObject>
    <label>Error Alert</label>
    <pluralLabel>Error Alerts</pluralLabel>
</CustomObject>

force-app/main/default/objects/PV_Error_Log__c/PV_Error_Log__c.object-meta.xml
<CustomObject>
    <label>PV Error Log</label>
    <nameField>
        <displayFormat>ERR-{00000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PV Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PV_Error_Log__c/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <label>Type Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ErrorAlertTriggerHelper.cls
public class ErrorAlertTriggerHelper {
    public static void afterInsert(List<Error_Alert__e> errorAlerts) {
        List<PV_Error_Log__c> errorLogsToInsert = new List<PV_Error_Log__c>();
        for (Error_Alert__e errorAlert : errorAlerts) {
            //create ErrorLogs
            PV_Error_Log__c newErrorLog = new PV_Error_Log__c(
                Line_Number__c = errorAlert.Line_Number__c,
                Message__c = errorAlert.Message__c,
                Stack_Trace__c = errorAlert.Stack_Trace__c,
                Type_Name__c	 = errorAlert.Type_Name__c
            );
            errorLogsToInsert.add(newErrorLog);
        }
        
        insert errorLogsToInsert;
    }
}