force-app/main/default/objects/Error_Alert__e/Error_Alert__e.object-meta.xml
<CustomObject>
    <label>Error Alert</label>
    <pluralLabel>Error Alerts</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSL_Error_Alert__e/FSL_Error_Alert__e.object-meta.xml
<CustomObject>
    <description>Used to save records to the Error_Log__c object. (PVFSL-200)</description>
    <label>FSL Error Alert</label>
    <pluralLabel>FSL Error Alerts</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSL_Error_Alert__e/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <description>Name of the apex class or lightning web component in which the error occurred. (PVFSL-200)</description>
    <label>Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSL_Error_Alert__e/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>If internal, this is the error message from the exception + the line number, if API call, then it is the response. (PVFSL-200)</description>
    <label>Error</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FSL_Error_Alert__e/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <description>Provider selected by the user in Chuzo. Leave empty if not applicable. (PVFSL-200)</description>
    <label>Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSL_Error_Alert__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Determines if the error is coming from an API or if it is internal. (PVFSL-200)</description>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExceptionUtil.cls
public class ExceptionUtil {
    public static void publishException(String typeName, Integer lineNumber, String message, String stackTrace) {
        Error_Alert__e pe = new Error_Alert__e();
        pe.Type_Name__c = typeName;
        pe.Line_Number__c = lineNumber;
        pe.Message__c = message;
        pe.Stack_Trace__c = stackTrace;
        EventBus.publish(pe);
    }

    public static void publishFSLException(String type, String provider, String component, String error) {
        FSL_Error_Alert__e event = new FSL_Error_Alert__e();
        event.Type__c = type;
        event.Provider__c = provider;
        event.Component__c = component;
        event.Error__c = error;
        EventBus.publish(event);
    }

    public static Error_Alert__e prepareException(String typeName, Integer lineNumber, String message, String stackTrace) {
        Error_Alert__e pe = new Error_Alert__e();
        pe.Type_Name__c = typeName;
        pe.Line_Number__c = lineNumber;
        pe.Message__c = message;
        pe.Stack_Trace__c = stackTrace;
        return pe;
    }

    public static void publishExceptions(List<Error_Alert__e> errorAlerts) {
        EventBus.publish(errorAlerts);
    }
}