force-app/main/default/objects/Error_Alert__e/Error_Alert__e.object-meta.xml
<CustomObject>
    <label>Error Alert</label>
    <pluralLabel>Error Alerts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Object used to store error logs. (PER-2431)</description>
    <label>Chuzo Error Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chuzo Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <description>Name of the apex class or lightning web component in which the error occurred. (PER-2431)</description>
    <label>Component</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PV_Error_Log__c/PV_Error_Log__c.object-meta.xml
<CustomObject>
    <label>PV Error Log</label>
    <nameField>
        <displayFormat>ERR-{00000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PV Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PV_Error_Log__c/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <label>Type Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ExceptionUtilTest.cls
@isTest
public class ExceptionUtilTest {
    @isTest
    static void publishException_positive() {
        Test.startTest();
        ExceptionUtil.publishException('ExceptionUtil', 15, 'Test message', 'Test stackTrace String');
        Test.getEventBus().deliver();
        Test.stopTest();
        List<PV_Error_Log__c> lst_Exception = [SELECT Id FROM PV_Error_Log__c WHERE Type_Name__c = 'ExceptionUtil'];
        System.assert(!lst_Exception.isEmpty(), 'ErrorLog__c records');
    }

    @isTest
    static void publishExceptionsTest() {
        List<Error_Alert__e> errorAlerts = new List<Error_Alert__e>();
        Error_Alert__e errorAlert = ExceptionUtil.prepareException('ExceptionUtil', 15, 'Test message', 'Test stackTrace String');
        errorAlerts.add(errorAlert);

        Test.startTest();
        ExceptionUtil.publishExceptions(errorAlerts);
        Test.getEventBus().deliver();
        Test.stopTest();

        List<PV_Error_Log__c> lst_Exception = [SELECT Id FROM PV_Error_Log__c WHERE Type_Name__c = 'ExceptionUtil'];
        System.assert(!lst_Exception.isEmpty(), 'ErrorLog__c records');
    }

    @isTest
    static void publishFSLExceptionTest() {
        Test.startTest();
        ExceptionUtil.publishFSLException('Internal Error', 'FSL', ExceptionUtilTest.class.getName(), 'Test error message');
        Test.getEventBus().deliver();
        Test.stopTest();

        List<Error_Log__c> errorLogs = [SELECT Id FROM Error_Log__c WHERE Component__c = :ExceptionUtilTest.class.getName()];
        Assert.isTrue(!errorLogs.isEmpty(), 'No logs created in Error_Log__c.');
    }
}