force-app/main/default/objects/POE_Interaction_Tracker__c/POE_Interaction_Tracker__c.object-meta.xml
<CustomObject>
    <label>Interaction Tracker</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Interaction Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interaction Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/POE_Interaction_Tracker__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clicker Page</fullName>
            </value>
            <value>
                <fullName>Disposition Page</fullName>
            </value>
            <value>
                <fullName>First Interaction</fullName>
            </value>
            <value>
                <fullName>Door To Door Page</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/POE_Interaction_Tracker__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interaction Trackers</relationshipLabel>
    <relationshipName>Interaction_Trackers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/POEInteractionTracker.cls
global without sharing class POEInteractionTracker implements vlocity_cmt.VlocityOpenInterface {
    global Boolean invokeMethod(
        String methodName,
        Map<String, Object> inputMap,
        Map<String, Object> outMap,
        Map<String, Object> options
    ) {
        Boolean result = true;
        try {
            User us = [SELECT Id, Profile.Name, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
            List<POE_Interaction_Tracker__c> pastInt = [SELECT Id FROM POE_Interaction_Tracker__c WHERE Contact__c = :us.ContactId AND CreatedDate = TODAY];
            POE_Interaction_Tracker__c interaction = new POE_Interaction_Tracker__c();
            if (us.Profile.Name != 'System Administrator') {
                interaction.Contact__c = us.ContactId;
                if (pastInt.isEmpty()) {interaction.Action__c = 'First Interaction';}
                else {interaction.Action__c = 'Clicker Page';}
            }
            insert interaction;
        } catch (Exception e) {
            result = false;
        }
        return result;
    }
}