force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>PV-Order Parts</label>
    <nameField>
        <displayFormat>PV-LI-{00000000}</displayFormat>
        <label>Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PV-Order Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Line_Item__c</fullName>
    <formula>IF( MSP__c &lt;  Price__c    ,(&apos;&lt;html&gt;&lt;body&gt;&lt;div style=&quot;color: red;&quot;&gt;&lt;b&gt;&apos; &amp; TEXT(Price__c) &amp; &apos;&lt;/b&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;&apos;),
IF(MSP__c &gt;  Price__c,(&apos;&lt;html&gt;&lt;body&gt;&lt;div style=&quot;color: green;&quot;&gt;&lt;b&gt;&apos; &amp; TEXT(Price__c) &amp; &apos;&lt;/b&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;&apos;),
&quot;&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/MSP__c.field-meta.xml
<CustomField>
    <fullName>MSP__c</fullName>
    <label>MSP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/MSP_Price_Warning__c.field-meta.xml
<CustomField>
    <fullName>MSP_Price_Warning__c</fullName>
    <formula>IF( Price__c &lt; MSP__c,
IMAGE(&quot;/img/samples/flag_red.gif&quot;,&quot;red&quot;, 20, 20)+&quot; Part is below MSP &quot;,
IF( Price__c &gt; MSP__c,
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;yellow&quot;, 20, 20)+&quot; Part not below MSP &quot;,
IMAGE(&quot;/img/samples/flag_yellow.gif&quot;, &quot;green&quot;, 20, 20)+&quot; Part is same as MSP &quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MSP Price Warning</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/MSP_Not_Meet__c.field-meta.xml
<CustomField>
    <fullName>MSP_Not_Meet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MSP Not Meet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PV_OrderPartsTriggerHandler.cls
public without sharing class PV_OrderPartsTriggerHandler {
	
    public static void handleAfterDelete (Map<Id, Line_Item__c> oderLineItems ){
        Set<String> orderIds = new Set<String>();
        for(Line_Item__c lineItems : oderLineItems.values()){
            orderIds.add( lineItems.Order__c );
        }
        
       	Map<Id, List<Line_Item__c>> orderAndParts = new Map<Id, List<Line_Item__c>>();
        for(Line_Item__c parts : [SELECT Order__c, Id, Price__c, MSP_Price_Warning__c, MSP__c 
                                    FROM Line_Item__c 
                                   WHERE Order__c IN : orderIds] ){
            orderAndParts.put(parts.Order__c, new List<Line_Item__c>());
            if( orderAndParts.containsKey(parts.Order__c)){
               orderAndParts.get(parts.Order__c).add(parts);                        
            }                        
        }
        
        List<Order__c> order = new List<Order__c>();
        Map<String,Boolean> orderMSPUpdate = new  Map<String,Boolean>();
        for(Id orderId : orderAndParts.keySet()){
            for(Line_Item__c linePart : orderAndParts.get(orderId)){
                //order.add( new order__c( Id = linePart.Order__c,  MSP_Not_Meet__c  = false));	 
                 orderMSPUpdate.put(linePart.Order__c,false);
            	if(linePart.Price__c < linePart.MSP__c){
                  //  order.add( new order__c( Id = linePart.Order__c,  MSP_Not_Meet__c  = true));
                  orderMSPUpdate.put(linePart.Order__c,true);
                    Break;
                }
            }
        }
        for(String orderId:orderMSPUpdate.keyset()){
            order.add( new order__c( Id = orderId,  MSP_Not_Meet__c  = orderMSPUpdate.get(orderId)));
        }
        if(order.size() > 0){
           update order;
        }
    }
}