force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>PV-Order Parts</label>
    <nameField>
        <displayFormat>PV-LI-{00000000}</displayFormat>
        <label>Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PV-Order Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Fulfilled_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Fulfilled_Quantity__c</fullName>
    <label>Fulfilled Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item #</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>PV-Order Parts</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <label>Item Description</label>
    <length>3800</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Line_Item__c</fullName>
    <formula>IF( MSP__c &lt;  Price__c    ,(&apos;&lt;html&gt;&lt;body&gt;&lt;div style=&quot;color: red;&quot;&gt;&lt;b&gt;&apos; &amp; TEXT(Price__c) &amp; &apos;&lt;/b&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;&apos;),
IF(MSP__c &gt;  Price__c,(&apos;&lt;html&gt;&lt;body&gt;&lt;div style=&quot;color: green;&quot;&gt;&lt;b&gt;&apos; &amp; TEXT(Price__c) &amp; &apos;&lt;/b&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;&apos;),
&quot;&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Requested_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Requested_Quantity__c</fullName>
    <label>Requested Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.P10_Invoice_Account__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PV-Orders</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>NLR</fullName>
            </value>
            <value>
                <fullName>NLR4</fullName>
            </value>
            <value>
                <fullName>DAL</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>XYZ wh A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>PV-Product</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PV-Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>CONNECTED SOLUTIONS</fullName>
            </value>
            <value>
                <fullName>DAS</fullName>
            </value>
            <value>
                <fullName>DIST</fullName>
            </value>
            <value>
                <fullName>FIBER</fullName>
            </value>
            <value>
                <fullName>INTL</fullName>
            </value>
            <value>
                <fullName>NATIONAL</fullName>
            </value>
            <value>
                <fullName>VIASAT</fullName>
            </value>
            <value>
                <fullName>WIRELESS</fullName>
            </value>
            <value>
                <fullName>WISP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Item_Name_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Name_Number__c</fullName>
    <label>Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PV_Warehouse__c/PV_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>PV-Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PV_Warehouse__c/fields/Bin__c.field-meta.xml
<CustomField>
    <fullName>Bin__c</fullName>
    <label>Bin #</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PV_Warehouse__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <label>Part #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PV_Warehouse__c/fields/Quantity_At_Hand__c.field-meta.xml
<CustomField>
    <fullName>Quantity_At_Hand__c</fullName>
    <label>Quantity At Hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PV_FullFill_OrderPartsTest.cls
@isTest
private class PV_FullFill_OrderPartsTest {
    @testSetup static void createData(){
        
        Account testAccount = new Account(Name = 'Test Account',
                                          P10_Invoice_Account__c ='Account Test',
                                          Division__c = 'DOM');
        insert testAccount;      
        Product__c prod = new Product__c(Name = 'ZVSYNC-NA/ZeeVee, HD Digital Tuner/Decoder QAM',
                                         Item_Description__c = 'Product 1 Description',
                                         Item_Name_Number__c = 'ZVSYNC-NA');
        insert prod;
        PV_Warehouse__c wareHouse = new PV_Warehouse__c(Bin__c = 'A123',
                                                        Part__c = 'ZVSYNC-NA',
                                                        Name = 'DAL',
                                                        Quantity_At_Hand__c = 4);
        insert wareHouse;
        Order__c order = new Order__c(Account_Name__c = testAccount.Id,
                                      Warehouse__c = 'DAL');
        insert order;
        Line_Item__c lineItem = new Line_Item__c(Requested_Quantity__c = 3,
                                                 Item_Description__c = 'Product 1 Description',
                                                 Fulfilled_Quantity__c =3,
                                                 Order__c = order.Id,
                                                 Item__c = prod.Id);
        insert lineItem;       
    }  
  
    private static testMethod void testFullFilledParts(){
        List<Account> acc = [SELECT Id,Name,Division__c FROM Account WHERE Name = 'Test Account'];
        Order__c orders =[SELECT Id,Name,Account_Name__c,Warehouse__c FROM Order__c WHERE Account_Name__c =:acc];
        String oId =orders.Id;
        List<Product__c> products = [SELECT Id,Name,Item_Description__c,Item_Name_Number__c FROM Product__c WHERE Name LIKE '%ZVSYNC-NA/ZeeVee, HD Digital Tuner/Decoder QAM%'];
        List<Line_Item__c> lineItems = [SELECT Id,Requested_Quantity__c,Fulfilled_Quantity__c,Item_Description__c,Order__r.Name,Order__r.Warehouse__c,Item__r.Item_Name_Number__c FROM Line_Item__c];
        List<PV_Warehouse__c> wareHouses = [SELECT Id,Name,Bin__c,Part__c,Quantity_At_Hand__c FROM PV_Warehouse__c WHERE Name ='DAL'];
        String store = PV_FullFill_OrderParts.getOrderPartsAndWarehouseInfo(oId);
        PV_FullFill_OrderParts.updateOrderParts(store);
        try{
        	PV_FullFill_OrderParts.updateOrderAndInventory(store,oId);
      	}catch(exception e){
		}     
        //PV_FullFill_OrderParts.updateOrderAndInventory(store,oid);
    }
}