force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>PV-Order Parts</label>
    <nameField>
        <displayFormat>PV-LI-{00000000}</displayFormat>
        <label>Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PV-Order Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Fulfilled_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Fulfilled_Quantity__c</fullName>
    <label>Fulfilled Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item #</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>PV-Order Parts</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <label>Item Description</label>
    <length>3800</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Line_Item__c</fullName>
    <formula>IF( MSP__c &lt;  Price__c    ,(&apos;&lt;html&gt;&lt;body&gt;&lt;div style=&quot;color: red;&quot;&gt;&lt;b&gt;&apos; &amp; TEXT(Price__c) &amp; &apos;&lt;/b&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;&apos;),
IF(MSP__c &gt;  Price__c,(&apos;&lt;html&gt;&lt;body&gt;&lt;div style=&quot;color: green;&quot;&gt;&lt;b&gt;&apos; &amp; TEXT(Price__c) &amp; &apos;&lt;/b&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;&apos;),
&quot;&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Requested_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Requested_Quantity__c</fullName>
    <label>Requested Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>MSP Approval</fullName>
            </value>
            <value>
                <fullName>Credit Approval</fullName>
            </value>
            <value>
                <fullName>Ready For Picking</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Warehouse Hold</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>NLR</fullName>
            </value>
            <value>
                <fullName>NLR4</fullName>
            </value>
            <value>
                <fullName>DAL</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>XYZ wh A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>PV-Product</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PV-Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Item_Name_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Name_Number__c</fullName>
    <label>Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PV_Warehouse__c/PV_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>PV-Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PV_Warehouse__c/fields/Bin__c.field-meta.xml
<CustomField>
    <fullName>Bin__c</fullName>
    <label>Bin #</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PV_Warehouse__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <label>Part #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PV_Warehouse__c/fields/Quantity_At_Hand__c.field-meta.xml
<CustomField>
    <fullName>Quantity_At_Hand__c</fullName>
    <label>Quantity At Hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PV_FullFill_OrderParts.cls
public with sharing class PV_FullFill_OrderParts {

@AuraEnabled
public static void updateOrderParts(String orderPartsToUpdate){
    List<PartsWrapper> partsToUpdate = (List<PartsWrapper>) JSON.deserialize (orderPartsToUpdate,List<PartsWrapper>.class);
    List<Line_Item__c> lineItem = new List<Line_Item__c>();
    List<PV_Warehouse__c> warehouseList = new List<PV_Warehouse__c>();
    Map<String,Integer> inventoryInfo = new Map<String,Integer>();

    for(PartsWrapper partwrap: partsToUpdate){
        System.debug('partwrap '+partwrap);
        List<String> ids = new List<String>();
        ids = partwrap.partId.split('--');
        if(String.isNotBlank(partwrap.partFullFillQty)){
            lineItem.add( new Line_Item__c( id = ids[0], Fulfilled_Quantity__c = integer.valueOf(partwrap.partFullFillQty)));
            inventoryInfo.put(ids[1], integer.valueOf(partwrap.partFullFillQty));
        }
        
    }
    if(lineItem.size()> 0){
        update lineItem;
    }
    /*for(PV_Warehouse__c wh: warehouseQuantityCheck(inventoryInfo.keySet())){
        System.debug('Quantity_At_Hand__c '+wh.Quantity_At_Hand__c);
        System.debug('inventoryInfo '+inventoryInfo.get(wh.Id));
        warehouseList.add(new PV_Warehouse__c(Id = wh.Id,Quantity_At_Hand__c = wh.Quantity_At_Hand__c - inventoryInfo.get(wh.Id)));
        System.debug('warehouseList inside for '+warehouseList);        
    }
    System.debug('warehouseList '+warehouseList);
    if(warehouseList.size()>0){
        update warehouseList;
    }*/    
}


@AuraEnabled
public static void updateOrderAndInventory(String orderPartsToUpdate, String orderId){
    try {

        if(String.isNotBlank(orderId)){
            Order__c ord = new Order__c( id = orderId, Stage__c = 'Fulfilled' );
            update ord;
        }

        List<PartsWrapper> partsToUpdate = (List<PartsWrapper>) JSON.deserialize (orderPartsToUpdate,List<PartsWrapper>.class);
        List<PV_Warehouse__c> warehouseList = new List<PV_Warehouse__c>();
        Map<String,Integer> inventoryInfo = new Map<String,Integer>();

        for(PartsWrapper partwrap: partsToUpdate){
            List<String> ids = new List<String>();
            ids = partwrap.partId.split('--');
            if(String.isNotBlank(partwrap.partFullFillQty)){
                inventoryInfo.put(ids[1], integer.valueOf(partwrap.partFullFillQty));
            }
        }

        for(PV_Warehouse__c wh: warehouseQuantityCheck(inventoryInfo.keySet())){
            warehouseList.add(new PV_Warehouse__c(Id = wh.Id,Quantity_At_Hand__c = wh.Quantity_At_Hand__c - inventoryInfo.get(wh.Id)));
        }
        if(warehouseList.size()>0){
            update warehouseList;
        }

    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
}

@AuraEnabled
public static String getOrderPartsAndWarehouseInfo(String orderId){
    List<PartsWrapper> partsInfos = new List<PartsWrapper>();
    List<Line_Item__c> lineItems = getOrderPartLines(orderId);
    String warehouseName;
    Set<String> allItems = new Set<String>();
    List<Order__c> ord= [SELECT Id,Name from Order__c where id=:orderId limit 1];
    String ordNumber=ord[0].Name;
    for(Line_Item__c lineItem : lineItems){
        if(String.isBlank(warehouseName)){
            warehouseName = lineItem.Order__r.Warehouse__c;
        }
        allItems.add(lineItem.Item__r.Item_Name_Number__c );
    }
    Map<String, PV_Warehouse__c> wareHousepartAndDetails = new Map<String, PV_Warehouse__c> ();
    for(PV_Warehouse__c warehouse : getWarehouseInfo(warehouseName, allItems)){
        wareHousepartAndDetails.put(warehouse.Part__c, warehouse);
    }    
    for(Line_Item__c line_Item :  getOrderPartLines(orderId)){
        PartsWrapper partsInfo = new PartsWrapper();
            partsInfo.partName          = line_Item.Item__r.Item_Name_Number__c;
            partsInfo.partReqQty        = String.valueof(line_Item.Requested_Quantity__c);
            partsInfo.partDescription   = line_Item.Item_Description__c;
            partsInfo.partFullFillQty   = line_Item.Fulfilled_Quantity__c!=null?String.valueof(line_Item.Fulfilled_Quantity__c):String.valueof(line_Item.Requested_Quantity__c);
            partsInfo.orderNumber       = ordNumber;
            partsInfo.partBin           = wareHousepartAndDetails.containsKey(line_Item.Item__r.Item_Name_Number__c)?wareHousepartAndDetails.get(line_Item.Item__r.Item_Name_Number__c).Bin__c:'';
            partsInfo.partWarehouseQty  = wareHousepartAndDetails.containsKey(line_Item.Item__r.Item_Name_Number__c)?String.valueof(wareHousepartAndDetails.get(line_Item.Item__r.Item_Name_Number__c).Quantity_At_Hand__c):'';
            partsInfo.inventoryId		= wareHousepartAndDetails.containsKey(line_Item.Item__r.Item_Name_Number__c)?String.valueof(wareHousepartAndDetails.get(line_Item.Item__r.Item_Name_Number__c).Id):'';
            partsInfo.partId			= line_Item.Id+'--'+partsInfo.inventoryId;
        partsInfos.add(partsInfo);
    }
    return JSON.serialize(partsInfos);
}

public static List<Line_Item__c> getOrderPartLines(String orderId){
    return [SELECT  Id, Requested_Quantity__c,
            		Fulfilled_Quantity__c,
                    Item__r.Name, 
                    Item_Description__c,
                    Order__r.Warehouse__c, 
                    Item__r.Item_Name_Number__c 
                FROM Line_Item__c WHERE Order__c = :orderId];
}

public static List<PV_Warehouse__c> getWarehouseInfo(String warehouseName, Set<String> itemNumbers){
    return [SELECT  Id, 
                    Bin__c, 
                    Part__c, 
                    Name, 
                    Quantity_At_Hand__c 
            FROM PV_Warehouse__c 
            WHERE Name = :warehouseName AND Part__c IN : itemNumbers];
}

public static List<PV_Warehouse__c> warehouseQuantityCheck(Set<String> warehouseId){
    return [SELECT  Id, 
                    Quantity_At_Hand__c 
            FROM PV_Warehouse__c 
            WHERE Id IN :warehouseId];
}

public class PartsWrapper{
    public string partId;
    public string partName;
    public string partDescription;
    public string partReqQty;
    public string partFullFillQty;
    public string orderNumber;
    public string partBin;
    public string partWarehouseQty;
    public string inventoryId;

}
}