force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>PV-Order Parts</label>
    <nameField>
        <displayFormat>PV-LI-{00000000}</displayFormat>
        <label>Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PV-Order Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item #</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>PV-Order Parts</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Line_Item__c</fullName>
    <formula>IF( MSP__c &lt;  Price__c    ,(&apos;&lt;html&gt;&lt;body&gt;&lt;div style=&quot;color: red;&quot;&gt;&lt;b&gt;&apos; &amp; TEXT(Price__c) &amp; &apos;&lt;/b&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;&apos;),
IF(MSP__c &gt;  Price__c,(&apos;&lt;html&gt;&lt;body&gt;&lt;div style=&quot;color: green;&quot;&gt;&lt;b&gt;&apos; &amp; TEXT(Price__c) &amp; &apos;&lt;/b&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;&apos;),
&quot;&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/MSP__c.field-meta.xml
<CustomField>
    <fullName>MSP__c</fullName>
    <label>MSP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Requested_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Requested_Quantity__c</fullName>
    <label>Requested Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.P10_Invoice_Account__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PV-Orders</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Mode_of_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Delivery__c</fullName>
    <label>Mode of Delivery</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ground</fullName>
                <default>true</default>
                <label>Ground</label>
            </value>
            <value>
                <fullName>Overnight</fullName>
            </value>
            <value>
                <fullName>LTL</fullName>
            </value>
            <value>
                <fullName>TQL</fullName>
            </value>
            <value>
                <fullName>CPU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>NLR</fullName>
            </value>
            <value>
                <fullName>NLR4</fullName>
            </value>
            <value>
                <fullName>DAL</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>XYZ wh A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>PV-Product</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PV-Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>CONNECTED SOLUTIONS</fullName>
            </value>
            <value>
                <fullName>DAS</fullName>
            </value>
            <value>
                <fullName>DIST</fullName>
            </value>
            <value>
                <fullName>FIBER</fullName>
            </value>
            <value>
                <fullName>INTL</fullName>
            </value>
            <value>
                <fullName>NATIONAL</fullName>
            </value>
            <value>
                <fullName>VIASAT</fullName>
            </value>
            <value>
                <fullName>WIRELESS</fullName>
            </value>
            <value>
                <fullName>WISP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Minimum_Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Selling_Price__c</fullName>
    <label>Minimum Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PV_OrderPartsHandlerTestClass.cls
@isTest
private class PV_OrderPartsHandlerTestClass {
    @testSetUp static void setup(){
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
        testAccount.Division__c = 'DOM';
        testAccount.Region__c = 'COLR';
        testAccount.Territory__c = 'COLT';
        testAccount.P10_Invoice_Account__c = 'TestAccountDOM';
        insert testAccount;
        
        Account a = [SELECT id, Name ,Division__c FROM Account WHERE Division__c = 'DOM'];
        Order__c testOrder = new Order__c(Account_Name__c = a.Id, 
                                          Mode_of_Delivery__c = 'Ground',
                                          Warehouse__c = 'CA');
        insert testOrder;
        
        Product__c testProduct = new Product__c(Name = 'Test Order',
                                                Minimum_Selling_Price__c = 500, 
                                                List_Price__c = 700);
        insert testProduct;
        
        Product__c p = [SELECT id,Name,Minimum_Selling_Price__c,List_Price__c FROM Product__c WHERE Name = 'Test Order'];
        Order__c o = [SELECT id, Mode_of_Delivery__c,Warehouse__c FROM Order__c WHERE Warehouse__c = 'CA'];
        
        Line_Item__c testLineItem1 = new Line_Item__c(Order__c = o.Id,
                                                      Price__c = 450,
                                                      MSP__c = 500,
                                                      Item__c = p.Id,
                                                      Requested_Quantity__c=1);
        insert testLineItem1;
        Line_Item__c testLineItem2 = new Line_Item__c(Order__c = o.Id,
                                                      Price__c = 400,
                                                      MSP__c = 500,
                                                      Item__c = p.Id,
                                                      Requested_Quantity__c=1);
        insert testLineItem2; 
    }
    private static testMethod void afterDeleteMethod(){
        Line_Item__c l1 = [SELECT id, Order__c,Price__c,Item__c,Requested_Quantity__c FROM Line_Item__c WHERE Price__c = 450];
        delete l1;
    }
}