force-app/main/default/objects/POE_Chuzo_Regular_Expressions__mdt/POE_Chuzo_Regular_Expressions__mdt.object-meta.xml
<CustomObject>
    <label>Chuzo Regular Expression</label>
    <pluralLabel>Chuzo Regular Expressions</pluralLabel>
</CustomObject>

force-app/main/default/objects/POE_Chuzo_Regular_Expressions__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Error message displayed when the regular expression is not met by the input.</description>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE_Chuzo_Regular_Expressions__mdt/fields/RegEx__c.field-meta.xml
<CustomField>
    <fullName>RegEx__c</fullName>
    <label>RegEx</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/POE_RegExObtainer.cls
public with sharing class POE_RegExObtainer {
    @AuraEnabled(cacheable=true)
    public static ResponseWrapper getOnlyLettersRegEx() {
        try {
            ResponseWrapper res = new ResponseWrapper();

            POE_Chuzo_Regular_Expressions__mdt regex = POE_Chuzo_Regular_Expressions__mdt.getInstance('Only_Letters');

            res.result = new Map<String, Object>{ 'expression' => regex.RegEx__c, 'errorMessage' => regex.Error_Message__c };
            return res;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class ResponseWrapper {
        @AuraEnabled
        public Map<String, Object> result;
    }
}